### ISSUE TITLE
using animation makes body align with head

### ISSUE THREAD

**Issue by RyanCR03** [tr7zw/NotEnoughAnimations#1]
using an animation that this mod adds makes the body align with the head.

**Comment by RyanCR03** [comment]
the only animation that doesnt do this are maps

**Comment by tr7zw** [comment]
Yea for the eating/drinking I did that to prevent the player stuffing the food into his ear or so, the shield is the main fix I've done this for. The compass is for the firstperson useability, but actually I might remove it there to make it equal to the maps.

**Comment by tr7zw** [comment]
Or to explain it the other way around: not all animations should do that. Now the question becomes, should maps do that? Personally I prefer it to be more dynamic since it looks a lot better. For the First-person Mod a point could be made that it's a lot simpler to use while walking/looking around if locked, so I guess making it an option there to lock the body for yourself when using a map/compass is a better idea.

**Comment by RyanCR03** [comment]
the players arm is too long to do that?
![image](https://user-images.githubusercontent.com/32957560/103704700-51f66b00-4f6f-11eb-899a-897a44d77e1f.png)

**Comment by tr7zw** [comment]
Yea I can't magically bend the arm, so this is as close as it gets(also what bedrock uses). I'd argue that it's better than nothing like vanilla java does.

**Comment by RyanCR03** [comment]
can you at least add a config?

**Comment by tr7zw** [comment]
For?

**Comment by RyanCR03** [comment]
and also can you add configs to stop some of the animations? i don't like the shield one...

**Comment by tr7zw** [comment]
I'll add configs for everything when also porting it to forge probably, for now the goal was it to keep it simple. The shield change is mostly to for the firstperson mod(since else your shield drifts around whereever), and to reflect how the shield ACTUALLY works with how it looks like.

**Comment by RyanCR03** [comment]
I misread what you said earlier what I meant by the arm being too long was having the rotation lock on wouldn't stuff the food into the ear

**Comment by tr7zw** [comment]
Ah yea that was meant more in general. While eating the head shouldn't move left and right. I can probably make it an option then too, but especially in the context of the firstperson mod it made more sense to have it locked like that, to prevent the animation of stuffing the food into the eye/camera.

**Comment by RyanCR03** [comment]
i thought you were going to make an option?

**Comment by tr7zw** [comment]
You mean eating/drinking locking? It will be.

**Comment by RyanCR03** [comment]
ok, btw i found a bug where if you eat or shield in a boat you spin like crazy...

**Comment by tr7zw** [comment]
I think I've fixed that already, but maybe I only fixed it inside the first-person mod, I'll take a look and fix it if it's still in there.
