### ISSUE TITLE
Elytra flying animation does not work if Personality mod by Team Abnormals is installed

### ISSUE THREAD

**Issue by RHSD** [tr7zw/NotEnoughAnimations#10]
Every other animation works but when flying with elytra it moves arms and legs as if running extremely fast.
https://www.curseforge.com/minecraft/mc-mods/personality
Mentioned here #9

**Comment by tr7zw** [comment]
Does this also happen when both this/the Firstperson mod is not installed? Since if that's the case the issue should be over here https://github.com/team-abnormals/personality .

**Comment by RHSD** [comment]
Ahh. You are absolutely right. This is completely a problem on their end. My bad
