### ISSUE TITLE
Modrinth upload

### ISSUE THREAD

**Issue by RaptaG** [tr7zw/NotEnoughAnimations#101]
Modrinth is an open-source mod distributing platform with a very good API. It also loads faster than CurseForge and has less ads. I believe it worths to upload it there as well.

**Comment by tr7zw** [comment]
https://modrinth.com/mod/not-enough-animations 👀. And at least for devs imo it currently sucks more than CurseForge.

**Comment by RaptaG** [comment]
> https://modrinth.com/mod/not-enough-animations 👀. And at least for devs imo it currently sucks more than CurseForge.

Hey sorry, for a reason I couldn't find them but never mind thanks!
