### ISSUE TITLE
Double hand creates extra hand when holding a map

### ISSUE THREAD

**Issue by ohnecksThing** [tr7zw/NotEnoughAnimations#105]
I don't remember if this issue was addressed before, but...
If you turn on Double hands and take a filled map in your main hand having no item in offhand (it's right in my case because I use left hand as main), the offhand is still displayed as a separate part despite player using both arms for the map.
![2022-07-18_10 54 46](https://user-images.githubusercontent.com/82406050/179438942-9d05f395-c957-4ff4-a293-6b69058d9637.png)
![2022-07-18_10 54 48](https://user-images.githubusercontent.com/82406050/179438947-5ff5fed2-a591-4b81-aec1-1f1e3c48bfc1.png)
![2022-07-18_10 54 50](https://user-images.githubusercontent.com/82406050/179438951-e5ca8190-aecd-4f6a-9790-7960551fbccc.png)

**Comment by tr7zw** [comment]
This is tracked over at FirstPersonMod(since it technically has nothing to do with NEA).
