### ISSUE TITLE
Crashes in Forge 1.19

### ISSUE THREAD

**Issue by treasboi** [tr7zw/NotEnoughAnimations#107]
hi dear developer,
when i try to open game it crashes or gives me message called "NotEnoughAnimations mod has failed to load correctly" how can we fix this error?

thanks

[crash-2022-08-02_10.55.31-fml.txt](https://github.com/tr7zw/NotEnoughAnimations/files/9240163/crash-2022-08-02_10.55.31-fml.txt)
![2022-08-02_10 55 37](https://user-images.githubusercontent.com/106917706/182322881-7d32c63e-ebae-4313-8eba-5fa4f3bf7758.png)
[latest.log](https://github.com/tr7zw/NotEnoughAnimations/files/9240179/latest.log)

**Comment by tr7zw** [comment]
Known issue. Forge broke all mods with a config screen. For now, wait for the 1.19.1 update, downgrade to version .63 or give fabric a try.
