### ISSUE TITLE
[Bug]Animation error while swimming

### ISSUE THREAD

**Issue by weirdo1275** [tr7zw/NotEnoughAnimations#109]
When attacking the left hand animation while swimming motion is wrong. This may be hard to spot in 1st person, but when you switch to 2nd and 3rd person you can clearly see the wrong left arm animation

https://user-images.githubusercontent.com/109478582/184346180-0af389e7-b5fd-415d-b2fc-6083639d368e.mp4

**Comment by Xoouu** [comment]
Yep, still happens in the latest version. I find it funny anyways.

**Comment by zndrmn** [comment]
Is this a dead issue because this is still a problem

**Comment by tr7zw** [comment]
I'm currently on this one before releasing the next version, as it (now?) also happens while crawling on land.

**Comment by zndrmn** [comment]
alright sweet!

**Comment by tr7zw** [comment]
Turns out this was a few glaring fuckups in the smoothing logic.

**Comment by zndrmn** [comment]
YYaaayy
