### ISSUE TITLE
Animation Smoothing Speed Inconsistent With Shaders

### ISSUE THREAD

**Issue by TypicalFoxxo** [tr7zw/NotEnoughAnimations#111]
It seems that the animation smoothing speed acts strangely when shaders are active with Optifine+Forge in 1.18. The speed slightly changes, but usually is just really slow and sluggish. When there aren't any shaders on, however, it's normal. Changing the smoothing speed in the config does nothing to fix it. 

shaders:
https://user-images.githubusercontent.com/112323973/187193941-311558c0-f123-44c4-8e29-f4687cd49afe.MOV

no shaders:
https://user-images.githubusercontent.com/112323973/187194022-d8fa071a-83a1-4f2d-9fd9-2fbaef2e6abe.MOV

**Comment by tr7zw** [comment]
Fixed
