### ISSUE TITLE
[Suggestion] Advanced Netherite mod improvement

### ISSUE THREAD

**Issue by MOOOOs** [tr7zw/NotEnoughAnimations#112]
Can you add Advanced Netherite mod swords to "Scabbard" when not in use? I love this mod but missing that detail with AN swords. Thanks

**Comment by tr7zw** [comment]
Add the sword id to the config file in the config folder white mc is closed.

**Comment by MOOOOs** [comment]
Thanks for quick reply and fix :)

**Comment by MOOOOs** [comment]
Oh i did put ids but when loading game mod creates new file any suggestions?

**Comment by tr7zw** [comment]
It will recreate the file if its not loadable(invalid json). Check that the ``,`` between the entries is right(the last one has none).

**Comment by MOOOOs** [comment]
i add like that
 	"advancednetherite:netherite_iron_sword"
	"advancednetherite:netherite_gold_sword"
	"advancednetherite:netherite_emerald_sword"
	"advancednetherite:netherite_diamond_sword"

**Comment by tr7zw** [comment]
No, you are missing the ``,``.  Every entry but the last needs a ``,``.

**Comment by MOOOOs** [comment]
here how it looks 
{
  "configVersion": 8,
  "animationSmoothingSpeed": 20.0,
  "holdingItems": [
    "minecraft:clock",
    "minecraft:recovery_compass",
    "minecraft:soul_lantern",
    "minecraft:compass",
    "minecraft:torch",
    "minecraft:lantern",
    "minecraft:soul_torch"
  ],
  "enableAnimationSmoothing": true,
  "enableInWorldMapRendering": true,
  "enableOffhandHiding": true,
  "enableRotationLocking": true,
  "enableLadderAnimation": true,
  "ladderAnimationAmplifier": 0.35,
  "ladderAnimationArmHeight": 1.7,
  "ladderAnimationArmSpeed": 2.0,
  "enableRotateToLadder": true,
  "enableEatDrinkAnimation": true,
  "enableRowBoatAnimation": true,
  "enableHorseAnimation": true,
  "dontHoldItemsInBed": true,
  "freezeArmsInBed": true,
  "rotationLock": "NONE",
  "showLastUsedSword": true,
  "sheathSwords": [
    "minecraft:golden_sword",
    "minecraft:iron_sword",
    "minecraft:wooden_sword",
    "minecraft:stone_sword",
    "minecraft:diamond_sword",
    "minecraft:netherite_sword"
	"advancednetherite:netherite_iron_sword"
	"advancednetherite:netherite_gold_sword"
	"advancednetherite:netherite_emerald_sword"
	"advancednetherite:netherite_diamond_sword"
  ],
  "enableCrawlingAnimation": true,
  "holdUpAllItems": false,
  "itemSwapAnimation": true,
  "tweakElytraAnimation": true,
  "petAnimation": true,
  "fallingAnimation": false,
  "freezingAnimation": true,
  "huggingAnimation": false,
  "narutoRunning": false,
  "enableInWorldBookRendering": false,
  "disableLegSmoothing": false
}

**Comment by MOOOOs** [comment]
oh i got what you mean

**Comment by tr7zw** [comment]
```
{
"configVersion": 8,
"animationSmoothingSpeed": 20.0,
"holdingItems": [
"minecraft:clock",
"minecraft:recovery_compass",
"minecraft:soul_lantern",
"minecraft:compass",
"minecraft:torch",
"minecraft:lantern",
"minecraft:soul_torch"
],
"enableAnimationSmoothing": true,
"enableInWorldMapRendering": true,
"enableOffhandHiding": true,
"enableRotationLocking": true,
"enableLadderAnimation": true,
"ladderAnimationAmplifier": 0.35,
"ladderAnimationArmHeight": 1.7,
"ladderAnimationArmSpeed": 2.0,
"enableRotateToLadder": true,
"enableEatDrinkAnimation": true,
"enableRowBoatAnimation": true,
"enableHorseAnimation": true,
"dontHoldItemsInBed": true,
"freezeArmsInBed": true,
"rotationLock": "NONE",
"showLastUsedSword": true,
"sheathSwords": [
"minecraft:golden_sword",
"minecraft:iron_sword",
"minecraft:wooden_sword",
"minecraft:stone_sword",
"minecraft:diamond_sword",
"minecraft:netherite_sword",
"advancednetherite:netherite_iron_sword",
"advancednetherite:netherite_gold_sword",
"advancednetherite:netherite_emerald_sword",
"advancednetherite:netherite_diamond_sword"
],
"enableCrawlingAnimation": true,
"holdUpAllItems": false,
"itemSwapAnimation": true,
"tweakElytraAnimation": true,
"petAnimation": true,
"fallingAnimation": false,
"freezingAnimation": true,
"huggingAnimation": false,
"narutoRunning": false,
"enableInWorldBookRendering": false,
"disableLegSmoothing": false
}
```
