### ISSUE TITLE
[1.18.2] Compatibility with Eating Animation [Forge]

### ISSUE THREAD

**Issue by INooBTooMuch** [tr7zw/NotEnoughAnimations#113]
If its possible to add compatibility for [Eating Animation [Forge]](https://www.curseforge.com/minecraft/mc-mods/eating-animation-forge).

**Comment by tr7zw** [comment]
What part of it isn't compatible?

**Comment by INooBTooMuch** [comment]
So I just tested it, its not the base mod its the addon "Eating Animations+". It think its a datapack but I don't know, its in the Resource Pack section in the CurseForge app. (Eating Animations+ by frogbirdd)

**Comment by tr7zw** [comment]
I mean, all they do is animate the item texture while it's getting eaten. That should work perfectly fine with the 3rd person animation.

**Comment by INooBTooMuch** [comment]
Then I guess its the addon not having a 3rd person animation, thnx.

**Comment by tr7zw** [comment]
The eating animation plays when it's turned on, and the vanilla "eating" mode is enabled. So if some mod doesn't use that and implements their own stuff, that won't work.
