### ISSUE TITLE
Compatibility mods "AntiqueAtlas" and " NotEnoughAnimations"

### ISSUE THREAD

**Issue by Mokich** [tr7zw/NotEnoughAnimations#115]
I would like to ask if it is possible to make support for the "AntiqueAtlas" mod?
![image](https://user-images.githubusercontent.com/114140584/191690525-ba25e15e-c274-4ac0-8ab0-e0b0219b0d07.png)
I would really like it to be in this mod

**Comment by tr7zw** [comment]
Up to AntiqueAtlas. I helped them with a pr that implements it(that's why from my end the map is already held up), just missing that they render the map into the world. Afaik that pr has been abandoned for a long time.
