### ISSUE TITLE
Update Minecraft version tags for Modrinth

### ISSUE THREAD

**Issue by BelisariusMC** [tr7zw/NotEnoughAnimations#116]
Add the tag for Minecraft version 1.19.2 on [Modrinth](https://modrinth.com/mod/not-enough-animations/version/1.6.1-fabric-1.19). The 1.6.1 mod version for Fabric works perfectly fine in these Minecraft, as I tested.

**Comment by tr7zw** [comment]
Fixed. It's a bit of a pain in the ass, 8 mods * 2 mod loaders * 2 platforms, and everywhere you need to set the checkbox for new mc releases 🙃
