### ISSUE TITLE
Text hover

### ISSUE THREAD

**Issue by Psychodeus** [tr7zw/NotEnoughAnimations#117]
![image](https://user-images.githubusercontent.com/93028949/196313325-65629b3a-9c2a-478c-9173-59aef7165eb3.png)
Could you please explain each settings? Or at least give hover text information about the settings?
Perhaps you could do me a favor by explaing it here? About simple huging, in-book world, and hold up all items.
Thanks.

**Comment by azzRPG** [comment]
In-world books allows you to see the books in that position, and what is written in them. But this only works with the First-person Model mod.
![image](https://user-images.githubusercontent.com/118481158/210450594-64e96fe4-4605-4f4e-8ba7-5b7ad0a46e61.png)
Unfortunately, I don't know about the other settings either.

**Comment by tr7zw** [comment]
Hover text was added some time ago.
