### ISSUE TITLE
Sword shows on side when not in inventory

### ISSUE THREAD

**Issue by Pixle36** [tr7zw/NotEnoughAnimations#121]
Swords will display on the side even if theres not one in the inventory

**Comment by tr7zw** [comment]
This feature just shows the last known sword a player held since it can't see the inventory of other players. Yea I could check for yourself, but then it would just desync even more. Not a bug, intended side effect.

**Comment by E1ecti** [comment]
> This feature has been removed as it doesn't fit the mod and caused too much confusion/visual bugs.

Would it be possible to re-add this feature as an optional toggle, disabled by default? It gave the game a unique charm, and I'd really like to have it back.

**Comment by tr7zw** [comment]
It was an optional toggle the entire time it was a thing. So if anything, it will be moved out into its own mod.
