### ISSUE TITLE
Minecraft doesn't recognize TRLib

### ISSUE THREAD

**Issue by ghost** [tr7zw/NotEnoughAnimations#122]
Hi,
Long story short, NEA and TRLib don't work together. The last time they worked together was on the 23rd of October 2022 (today I decided to play and here we are...)
Forge version: 1.16.5 - 36.2.39
![image](https://user-images.githubusercontent.com/107777444/200553938-0d9ff538-e50f-4ac4-9f5a-bf3b7650caec.png)
![image](https://user-images.githubusercontent.com/107777444/200554432-7cd994ea-14ce-408d-a880-86f8cc57ff54.png)

**Comment by tr7zw** [comment]
1.16 is not supported anymore exactly because of the lib. Looks like some forge load order issue. Try just loading the lib and see if it shows up/different forge versions.

**Comment by NeroToge** [comment]
![image](https://user-images.githubusercontent.com/107777444/200556832-5a3fb624-4f3a-4ec1-853f-2f9593a19982.png)
![image](https://user-images.githubusercontent.com/107777444/200557179-5955709c-9422-437f-8851-5f9130eebdf9.png)
Works both alone and with NEA
Must be a compatibility issue with one of the mods I updated from the modpack I used.
![image](https://user-images.githubusercontent.com/107777444/200557550-47a55e56-b41e-4a86-8f54-b1009ad2ee04.png)
These are the mods that were updated (Geckolib was removed. It didn't work with and without it (I didn't need it anymore))

**Comment by tr7zw** [comment]
Closing this as the 1.16 version is about to be replaced.
