### ISSUE TITLE
Allow third party applications to download mod on CurseForge

### ISSUE THREAD

**Issue by xVANKO** [tr7zw/NotEnoughAnimations#124]
Hi,

Many people use mod managers like ferium to download and update their mods.
Currently your mod cant be downloaded, could you please allow this feature to be used?

![image](https://user-images.githubusercontent.com/62944093/206801005-d1a1ab1e-12c8-42a7-8332-03f0a26335d6.png)

**Comment by tr7zw** [comment]
No because curseforges api is really bad. Use modrinth for that, most clients will auto detect that.
