### ISSUE TITLE
Possible Incompatibility Issue with Xaero's Minimap

### ISSUE THREAD

**Issue by Rxnzoo** [tr7zw/NotEnoughAnimations#125]
Client crashing after hitting tab

Mentioned this to Xaero and he said this:
(also pastebin crash report: [https://pastebin.com/BzPgCe6u](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fBzPgCe6u)) 
![image](https://user-images.githubusercontent.com/54460708/207787884-968082af-1818-4408-b3c1-9f1fd2ceac48.png)

**Comment by tr7zw** [comment]
Caused by: java.lang.NullPointerException: Cannot invoke "com.pikachu.mods.vanilla_animations.interfaces.IGeoReplacedEntity.getMob()" because "object" is null

That's not this mod.
