### ISSUE TITLE
Wont work with Better Combat in Forge Multiplayer Server

### ISSUE THREAD

**Issue by Zufallig27** [tr7zw/NotEnoughAnimations#127]
I'm using Forge Version 1.19.2 with all 19,2 versions of mods and I can not for the life of me figure out why BC & NEA wont work in my multiplayer server, but works in Solo.
[crash-2023-01-10_16.42.04-fml.txt](https://github.com/tr7zw/NotEnoughAnimations/files/10387124/crash-2023-01-10_16.42.04-fml.txt)

**Comment by tr7zw** [comment]
This is a client-side only mod. Putting it into the server will indeed just crash it.

**Comment by Zufallig27** [comment]
Ah damn really, that sucks saw youtubers use it in videos like with the MC purge server just recently and thought saw them using it cause of the different ladder climbing animations.
