### ISSUE TITLE
(Suggestion) Proper bow animations

### ISSUE THREAD

**Issue by tehehe22** [tr7zw/NotEnoughAnimations#130]
Could you add/fix the bow animations since it's kinda lacking and doesn't really look right in first person.
![wAMvkIp](https://user-images.githubusercontent.com/123723090/215034109-196b1c49-ac46-4278-a95a-e7d2be6d93c0.png)
Here's an image of 1.6.4 First person mod and how they solved that issue.

**Comment by tr7zw** [comment]
Kinda duplicate of https://github.com/tr7zw/FirstPersonModel/issues/56 . The issue is a result of First person mod, not of this mod(the fix for the issue will be implemented here).
