### ISSUE TITLE
Alternate / multiple scabbard locations (SUGGESTION)

### ISSUE THREAD

**Issue by swuff-star** [tr7zw/NotEnoughAnimations#131]
It'd be awesome to see a back slot, used similarly to the scabbard for swords - namely for bows, crossbows, or other larger tools the player might put on their back. Ideally supporting multiple displays e.g. both a sword at the player's hip and their back item at the same time; BackTools is an example of this implementation that is unfortunately left on 1.16.

**Comment by tr7zw** [comment]
This feature is on the chopping block and will rather be removed than improved(like having tools on the back). The reason behind this: there are other mods that do it better with new slots/correct sync, and it doesn't even fit this mod(it's not an animation).
