### ISSUE TITLE
a mod incompatibility with this and mekanism

### ISSUE THREAD

**Issue by Acat1234** [tr7zw/NotEnoughAnimations#135]
For some reason the map doesn't work properly with the mekasuit bodyarmor which makes it not show the "map" just the non "upgraded" sprite 
 it might be that the reason that happens is because the mekasuit bodyarmor covers the full arms idk can that be fixed please?

**Comment by tr7zw** [comment]
I don't quiet understand what you mean. Can you add an image? The maps worth with te body armor? Wha does the body armor have to do with maps?

**Comment by robit4** [comment]
Ok I'm getting it right now

**Comment by robit4** [comment]
This is what I mean                                              [image:
2023-03-01_15.32.17.png]

**Comment by robit4** [comment]
![2023-03-01_15 32 17](https://user-images.githubusercontent.com/126712560/222291529-4acf5cf7-2027-4668-802a-66ade57cba6c.png)

**Comment by tr7zw** [comment]
Does it show up in f5? Is that an actual vanilla map? Is the setting on for the map to render?

**Comment by robit4** [comment]
Oh I will test that.

**Comment by robit4** [comment]
Here is a screenshot of the problem (before creation)
![2023-03-22_11 23 48](https://user-images.githubusercontent.com/126712560/227001739-1e72c77c-502c-4ae0-a93d-9067ca922333.png)
After creating (with mekasuit)
![2023-03-22_11 23 51](https://user-images.githubusercontent.com/126712560/227001933-da943a04-6a01-4ee3-bb19-3ca00d28c777.png)
After creating without mekasuit
![2023-03-22_11 23 58](https://user-images.githubusercontent.com/126712560/227002009-8b980109-afb3-4bf9-8244-06bf559c1388.png)
I hope this helps

**Comment by tr7zw** [comment]
And in F5?

**Comment by tr7zw** [comment]
But in general, for it to not render at all, it has to be some other hand renderer or not the player or something. Doubt I will try to fix this.

**Comment by robit4** [comment]
Dos that mean will fix or won't fix?

**Comment by tr7zw** [comment]
It's an obscure bug in combination with 3 mods(nea, fp and mekkanism), 1 modded item, and a non-critical feature and a vanilla item. The hours it would take to look into what's happening/to fix it is just not worth it.

**Comment by robit4** [comment]
Oh ok
