### ISSUE TITLE
[Question / Request ] 1.6.3 for 1.19.2

### ISSUE THREAD

**Issue by MarkinhosMLP** [tr7zw/NotEnoughAnimations#138]
im still playin in 1.19.2 and i dont know if all the new features from 1.6.3 version is relevant but the tooltip in config screen is really useful and i always like to keep my mods up to date, so i just wanna know if we will have it for 1.19.2 as well

so... are we gonna have it?? if not, is it possible to adapt it for 1.19.2?

**Comment by tr7zw** [comment]
Planned for some time later. I need to create some tooling to better maintain all these older versions, then 1.19.2 will get updates again.

**Comment by tr7zw** [comment]
Going to happen now.
