### ISSUE TITLE
Yet another incompatibility

### ISSUE THREAD

**Issue by robit4** [tr7zw/NotEnoughAnimations#139]
For some reason this mod removes the reload animation from mrcrafish's (sorry if I misspelled the name) gun mod so can that get fixed

**Comment by tr7zw** [comment]
Starting to get the urge to put mrcrafish's gunmod on the incompatible list for all of my mods, just in general/so I can close bugs reports about issues with it. Maybe try turning off the animation smoothing, only thing I could think of that might be related to that.

**Comment by robit4** [comment]
ok I will try that

**Comment by robit4** [comment]
It still doesn't work unfortunately :(

**Comment by tr7zw** [comment]
I mean, each feature of the mod is toggleable. Either one of these toggles fixes it, or its not this mod.

**Comment by robit4** [comment]
oh I will try

**Comment by robit4** [comment]
oh I tried turning off all the animations the mod adds, and it still doesn't work I will try removing the mod (the more animations mod) and try again ok?

**Comment by tr7zw** [comment]
Yea then try without the mod. I mean, this mod works with other animation mods like EmoteCraft and BetterCombat. So it JUST breaking the reload animation sounds off.
