### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EstlyCodes** [tr7zw/NotEnoughAnimations#140]
Is there a version of this mod that only has it so the sword goes on your belt? Nothing else in the mod?

**Comment by tr7zw** [comment]
No, and this feature will be removed sooner than later. There are other mods that do the same, or you can use this mod and just turn off all other features you don't want.

**Comment by EstlyCodes** [comment]
May I ask which other mods? I've been looking all over the place and I still haven't found one.

**Comment by tr7zw** [comment]
Back tools or so. But yea, you can also just use thod mod with everything else disabled(no clue why you'd want to do that, but you could).

**Comment by EstlyCodes** [comment]
Sorry that I keep asking questions but, what is thod mod? I searched it up and found nothing.

**Comment by tr7zw** [comment]
from a quick google
https://www.curseforge.com/minecraft/mc-mods/back-tools
https://www.curseforge.com/minecraft/mc-mods/backslot
https://modrinth.com/mod/weaponmaster

**Comment by EstlyCodes** [comment]
Ok thank you

**Comment by tr7zw** [comment]
Again, not sure why you'd want this feature, but not all the other visually better ones.
