### ISSUE TITLE
Request: Optional Bedrock Edition and Super Smash Bros. Ultimate styled Eating Animations

### ISSUE THREAD

**Issue by ThisGreenDingo** [tr7zw/NotEnoughAnimations#142]
Hi! Something that's bothered me for a little while is that the eating animation present in Not Enough Animations doesn't resemble the official ones present in Bedrock and Smash Bros. Both have slightly different arm rotations/positions. My personal favourite is the Bedrock animation, as it looks close to the Not Enough Animations one but with a slightly different and lower rotation. 

Having these two versions of the animation would be nice feature to have! It's subtle but I would like to use them regardless.

Here's some example videos of the two animations:
https://www.youtube.com/watch?v=T6CWuOnXcLI
https://www.youtube.com/watch?v=UexB-fjwC2Q

**Comment by DreamSt4n** [comment]
You can use Bedrockify mod for a similar eating animation to Bedrock.

**Comment by tr7zw** [comment]
Yea, I don't see much point in spending time trying to have it at a slightly different angle/choppy movement like that. If people really want that, Bedrockify already provides that. The current one uses the Java First Person movement, which is the premise of the mod.
