### ISSUE TITLE
Request: Vanilla Shield Blocking Toggle when Animation Smoothing is enabled

### ISSUE THREAD

**Issue by DreamSt4n** [tr7zw/NotEnoughAnimations#145]
Currently, when you block with a shield when Animation Smoothing is enabled, the third person animation doesn't fit well compared to its vanilla counterpart.

Could you make a toggle for the "instant" third person blocking with a shield in vanilla even with Animation Smoothing is enabled?

**Comment by DreamSt4n** [comment]
Futhermore, can you also add an option for instant switching of items in third person?

**Comment by tr7zw** [comment]
Huh?

**Comment by DreamSt4n** [comment]
I mean, can you add an option so that there isn't an animation when you switch an item in third person like in Vanilla? Those are the only two things that I would love to see added, although it might not be a popular idea.

**Comment by tr7zw** [comment]
I have no clue what you mean. There is no animation for switching an item. Do you maybe mean swapping the left and right hand?

**Comment by DreamSt4n** [comment]
Don't mind the skin, I'm not home so I am on a different setup and account.

https://user-images.githubusercontent.com/19875208/235783991-02900193-53cd-443c-b8a6-a3ffa8039c12.mov

**Comment by tr7zw** [comment]
Which animation?

**Comment by DreamSt4n** [comment]
The animation when I change items.

**Comment by tr7zw** [comment]
But there is none. The arms go up once because you held a crossbow and the crossbow is held up. There is no switching animation

**Comment by DreamSt4n** [comment]
Without NotEnoughAnimations:

https://user-images.githubusercontent.com/19875208/235784794-7aee92a3-96f2-4b0c-a490-1c6eed792dcd.mov

**Comment by DreamSt4n** [comment]
Basically, an option for the arms to instantly go to the position of the crossbow instead of being animated, which correlates to the shield blocking issue.

**Comment by tr7zw** [comment]
No can do. I can look rather it's possible to dynamically turn it off in certain cases, but this will be weeks/months away.

**Comment by DreamSt4n** [comment]
Why not? I don't see this as an issue.

**Comment by tr7zw** [comment]
Like I also mentioned in the dms, not that interested in doing this currently since personally I don't think it looks good and no one else so far asked for it, and busy with IRL/other mods.

**Comment by DreamSt4n** [comment]
Okay, I understand that.
