### ISSUE TITLE
[Suggestion] New walking animations

### ISSUE THREAD

**Issue by lxly9** [tr7zw/NotEnoughAnimations#146]
Basically new walking animations that are in line with the overhauled animations in this mod (e. g. crawling has detached legs). So detaching legs and more articulate arms while walking slowly and running!

**Comment by tr7zw** [comment]
Wrong mod? This mods crawling doesn't have detached legs, and that's explicitly the style it's going for. Also, it's about adding missing animations/fixing animations, not really overwriting vanilla ones like walking. You are probably looking for a different mod.
