### ISSUE TITLE
Limb shaking bug

### ISSUE THREAD

**Issue by Mongoldyne** [tr7zw/NotEnoughAnimations#151]
Limbs shaking whenever player is moving sideways, if "enableAnimationSmoothing" is true.
Video: https://github.com/tr7zw/NotEnoughAnimations/assets/120526282/499d12be-aea4-4f1d-84ae-ced41d449cde
Probably a mod conflict, but i am unable to detect the guilty one among the 200 of them.

Sorry if its all useless, just want you to know about the existence of bug. Appreciate your work

**Comment by tr7zw** [comment]
You have rotation locking on, thats why.

**Comment by Mongoldyne** [comment]
> You have rotation locking on, thats why.

Oh... yeah... on "smooth" setting
Thanks a lot
