### ISSUE TITLE
Mirrored movement on better minecraft modded server

### ISSUE THREAD

**Issue by Abduki** [tr7zw/NotEnoughAnimations#156]
When I use shaders, my minecraft modded in version 1.19.2 specificity better minecraft fabric keeps mirroring the actions of other players. What happens is that whenever I use shaders, and I believe it's with the Not enough animations mod, which animates player movement and such, whenever I perform an action such as punching, shifting, crouching, or holding a crossbow, the other player that I'm playing with mirrors all of my movements. When I disabled the not enough animations mod, the problem resolved itself and I no longer have it.  Any ideas on how I can proceed to resolve this issue?

**Comment by tr7zw** [comment]
This mod doesn't have any special handling/setting for crouching, so it sounds kinda wrong? Plus no one else reporting this issue. Please verify that this can be reproduced in any way.

**Comment by Abduki** [comment]
Fixed after I updated all my mods. I'll double check and do more experimenting before submiting an issue next time. Sorry

**Comment by tr7zw** [comment]
All right. It sounded a bit weird, that's why I asked again.

**Comment by B1BU** [comment]
I want to add I'm having the same issue and I also thought NotEnoughAnimations was the culprit, but it turns out it wasn't. I have no idea what is tho
