### ISSUE TITLE
Handheld book offset?

### ISSUE THREAD

**Issue by nopeless** [tr7zw/NotEnoughAnimations#158]
It seems that the text in the book has a terrible offset. I know this is an experimental feature, is it going to be fixed?

I'd like to know what the status of this feature is

I am willing to implement a fix

**Comment by tr7zw** [comment]
It's turned off by default and has a [WIP] tag for a reason. I tried to get the text as close as possible but faced issues with the origin not lining up between the book and text (causing them to rotate around different points). I haven't gotten around to looking deeper into it, fixing these issues.

**Comment by nopeless** [comment]
thank you so much. I'll check it out and tell you if I do work on a fix 👍

**Comment by tr7zw** [comment]
The text isnt even implemented anymore currently. Closing the issue since I dont know when this will be worked on again.
