### ISSUE TITLE
[1.19.2] Sheathing bug

### ISSUE THREAD

**Issue by Auuki** [tr7zw/NotEnoughAnimations#165]
When switching from a "sheathSwords" item to another, it briefly shows in the sheath position then disappears. The way I expected it to work was that the last used "sheathSwords" item would land in the sheath position. If that's not the case then at least the brief appearance is a bug.

**Comment by tr7zw** [comment]
sheathSwords is deprecated and removed/disabled by default in newer versions. Also sounds like you might have messed with the config file and have air in there or so?

**Comment by tr7zw** [comment]
Gonna close this as inactive, and since the feature is deprecated anyway.
