### ISSUE TITLE
Where is config menu in this mod?

### ISSUE THREAD

**Issue by iAskel** [tr7zw/NotEnoughAnimations#167]
How to get to the configuration menu. I have installed at least two of menu mods, but not one has access to the configurations of this mod. I need it mainly to activate crawling in the game, however I have not found any guides, settings or hints anywhere.

This modes for config i used:
https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption
and
https://www.curseforge.com/minecraft/mc-mods/configured
Second is only one mod for mod menu thats works in 1.16.5 with forge, first can access in many few mods, but even Configured with Catalogue from MrCryfish cant acess to your mod.

Im using Forge 1.16.5 through CurseForge launcher on windows 10.

**Comment by tr7zw** [comment]
Don't know if the 1.16 version has a config screen as it's entirely discontinued and unsupported for the past 2 soon 3 years. The config screen is accessed like any other mod on forge, via the modlist in the main menu, clicking on the mod and then settings.

**Comment by iAskel** [comment]
Yes in 1.16.5 mod menu doesnt work, i test with 1.20 and yes i have access to config of mod.

**Comment by tr7zw** [comment]
Then the 1.16 version just doesn't have one. You can edit the config file, but the 1.16 version barely has any features cause I said, dead for 2-3 years by now:
```
    public float animationSmoothingSpeed = 20f;
    public Set<String> holdingItems = new HashSet<>(Arrays.asList("minecraft:clock", "minecraft:compass", "minecraft:torch", "minecraft:lantern"));
    public boolean enableAnimationSmoothing = true;
    public boolean enableInWorldMapRendering = true;
    public boolean enableOffhandHiding = true;
    public boolean enableRotationLocking = true;
    public boolean enableLadderAnimation = true;
    public boolean enableEatDrinkAnimation = true;
    public boolean enableRowBoatAnimation = true;
    public boolean enableHorseAnimation = true;
    public boolean enableIngameMapHolding = true;
    ```

**Comment by iAskel** [comment]
Hmm i hear what 1.16.5 is the best with 1.12. First it have most of all mods, but I'm not sure because in curse and modrinth i see what now mods create in most for new version, maybe 1.16.5 and 1.12 were the most popular but now...but now I’m afraid everything’s the other way around. And second new version have higher system requirements, yes on my PC they are not particularly slow, but watch as the CPU load reaches 80% in 1.20, where in 1.16 it fluctuates around 20, while the graphics as you know in Minecraft in general almost do not change without installing mods. So I do not even know whether to move to the new versions 1.17 - 1.20...))

**Comment by iAskel** [comment]
Yes perhaps you are right about obsolescence, and I have long noticed that on fabric for 1.16.5 is really very few mods. And about the hardware I do not know, my PC is though not the most powerful: R5 2600 + GTX1660s + 16gb RAM + two m2 ssd (256gb + 5120gb) and Win10 of course. Resolution is 1080p, not 2k or 4k or something. Yeah i know what my nvidia card is not powrfull i agree but for what for witcher 3 yes especially with 2k monitor but for 1080p its ok (i mean old version not remaster with RTX). But for minecraft? I use shader but only water and it doesnt load my gpu very much + limit fps on 116 with 120hz. If i fly in creative mode i see my Cpu load in 1.16 and it show me 20-30% (with BD craft 128x128) and if i fly in 1.20 (Vanilla textures without mods) it look like 50-80% and for what i must pay? For dungeon generating blocks with 4 polygons and 2 textures?))) Maybe i try test 1.19.4 or another new version once again but buying i9 + 4090 for minecraft.... you serious?))) Or maybe i need change optifine to sodium or installing optimizations mods i dont know but...optimization of this game is real suck...

**Comment by iAskel** [comment]
> > Hmm i hear what 1.16.5 is the best with 1.12. First it have most of all mods, but I'm not sure because in curse and modrinth i see what now mods create in most for new version, maybe 1.16.5 and 1.12 were the most popular but now...but now I’m afraid everything’s the other way around.
> 
> These _were_ popular versions when they were the latest release(you can add 1.18 to the list too I guess). And yes they have a big amount of mods, but that doesn't mean that it's good. Most of these mods are unmaintained and outdated(And so is Forge/Fabric for these versions). 1.12 is mostly used for some old FTB Modpacks and I think Pixelmon, that's basically it. I wouldn't recommend trying to create anything new on that. Same with 1.16, Fabric devs basically all left that version, and on Forge it's just a small part of mods still caring.
> 
> > And second new version have higher system requirements, yes on my PC they are not particularly slow, but watch as the CPU load reaches 80% in 1.20, where in 1.16 it fluctuates around 20, while the graphics as you know in Minecraft in general almost do not change without installing mods. So I do not even know whether to move to the new versions 1.17 - 1.20...))
> 
> The changes are because mc gets updated to make use of modern hardware. So it runs a lot better on modern hardware(400+ fps in vanilla, easily 1000+ fps modded), while older hardware is slower in working with that. The inverse is true too, 1.8/7 with optifine runs like garbage on my PC, slower than 1.20 vanilla. So yes, the game feels like it gets slower with each update, but the issue is more that the hardware is also not keeping up to features when you are using a 10-year-old PC or even worse laptop. A good comparison is: 1.8 had no issue running on old laptops with integrated graphics, but 1.20 on the other hand is able to utilize a beefy GPU like a 3090, where 1.8 uses less than 10% of it.

Yes perhaps you are right about obsolescence, and I have long noticed that on fabric for 1.16.5 is really very few mods. And about the hardware I do not know, my PC is though not the most powerful: R5 2600 + GTX1660s + 16gb RAM + two m2 ssd (256gb + 5120gb) and Win10 of course. Resolution is 1080p, not 2k or 4k or something. Yeah i know what my nvidia card is not powrfull i agree but for what for witcher 3 yes especially with 2k monitor but for 1080p its ok (i mean old version not remaster with RTX). But for minecraft? I use shader but only water and it doesnt load my gpu very much + limit fps on 116 with 120hz. If i fly in creative mode i see my Cpu load in 1.16 and it show me 20-30% (with BD craft 128x128) and if i fly in 1.20 (Vanilla textures without mods) it look like 50-80% and for what i must pay? For dungeon generating blocks with 4 polygons and 2 textures?))) Maybe i try test 1.19.4 or another new version once again but buying i9 + 4090 for minecraft.... you serious?))) Or maybe i need change optifine to sodium or installing optimizations mods i dont know but...optimization of this game is real suck...

**Comment by tr7zw** [comment]
Talking from experience, the Ryzen 2600 is probably the issue. Before I had a Ryzen 1700 and rtx2070Super, and the the CPU bottlenecked the GPU hard. Best-case look into something like the 5600X, they are like 160€ on Amazon(cheaper used/potentially other sites) and waaaaay faster, plus you don't need to replace anything like motherboard/ram. (https://www.youtube.com/watch?v=Dy6w_Vd97xI see here with CPU-limited games(like Minecraft is), being csgo/rainbow6, where it easily can make 30-100% more fps, just replacing the 2600 with a 5600X).

**Comment by tr7zw** [comment]
Getting a new GPU wont do anything in your case since you are too bottlenecked on the CPU. Also closing this issue for now.
