### ISSUE TITLE
Slow movement barely visible 

### ISSUE THREAD

**Issue by leaR11** [tr7zw/NotEnoughAnimations#168]
Hello. When I install the mod for fabric my shaders make it impossible to see anything when I hit the arm is slow the walking looks like the legs are not moving same for the rest I use the bal shader 
What can I do if my shaders are the cause of my character barely moving?

**Comment by captinwill** [comment]
I don't know what causes this. I thought that this was caused by lower framerate from the refresh rate but I was wrong. For now though, this mod is incompatible with shaders.
