### ISSUE TITLE
Bows will misalign under severe left and right shaking

### ISSUE THREAD

**Issue by ZHEAIss** [tr7zw/NotEnoughAnimations#172]
![2023-12-30_10 18 48](https://github.com/tr7zw/NotEnoughAnimations/assets/154711805/25f3d2a1-4111-4c13-b3c3-105e4f4a67fc)
![2023-12-30_10 19 01](https://github.com/tr7zw/NotEnoughAnimations/assets/154711805/a31c155e-964d-4935-ba0d-d9250cd228ae)
When using custom v1, as shown in the figure. Although the arrow was fired at the cursor, its movements were confused (and I also found that raising the shield would reset to the correct action)

**Comment by ZHEAIss** [comment]
Oh, just open the fixed rotation lock and it will be fine

**Comment by tr7zw** [comment]
Afaik this should also be fixed in later versions.
