### ISSUE TITLE
[Bug] Player arms sometimes disappear and lose his rotational movement with shouldersurfing mod installed

### ISSUE THREAD

**Issue by ChrissPz** [tr7zw/NotEnoughAnimations#18]
Sometimes the player arm rotating wildly when I hold an object, just when i have shouldersurfing mod.
is this an incompatibility? let me know pls

https://user-images.githubusercontent.com/33664951/112712955-60d72480-8eb1-11eb-94be-5d6dd6b32cf4.mp4

**Comment by tr7zw** [comment]
Don't think this is related to shoulder surfing. Can you confirm that this still happens with 1.2.3?
