### ISSUE TITLE
Add config for adding other books

### ISSUE THREAD

**Issue by lxly9** [tr7zw/NotEnoughAnimations#184]
Basically the title, I would love to have a config in which i could specify all book items that should have a 3d version!

**Comment by tr7zw** [comment]
Basically the 3d book is only there for the vanilla writable book, and the plan is/was to display the books content on the 3d model. For modded books/any other books a normal resource pack can be used to just make them a 3d model.

**Comment by lxly9** [comment]
yeah that is true, but that would make the books also 3d in the inventory which i dont really like tbh :P I was also not thinking about the text rendering (that would be a nightmare) just the holding animation haha (maybe that could actually be 2 separate options?)

**Comment by tr7zw** [comment]
Resource packs can split that up to have a 2d one in the inventory.

**Comment by lxly9** [comment]
i thought that was only possible with block models as they have an inventory and handheld model path

**Comment by tr7zw** [comment]
Hm, never tried it, but I guess then it would be still more the case for another mod([CIT Resewn](https://modrinth.com/mod/cit-resewn)?)? I think if I'll ever pick up this feature again and try to get the font rendering to not suck, then I would remove the special logic for the other books like enchanted books(or put them behind another flag and do something else like adding text into them about the enchant, idk). 
But for other books from other mods, I don't think this would fit here. The mod is about adding missing animations to vanilla which fit the vanilla game. Other mods that contain books can just add a 3d model for them. It's like the 3rd person map holding, no one prevents other mods from doing that stuff with their custom maps either. Trying to hook a ton of other mods and making textures/models for them is not something I'm interested in, and not really the goal/point of this mod.

**Comment by lxly9** [comment]
That is true! I was rather thinking about just having the same model but i totally understand your point, that would be way out of scope! 
Btw Forge has split GUI and handheld models natively for resource packs, just all other loaders dont support that haha
