### ISSUE TITLE
When it supports snapspot 24w18a

### ISSUE THREAD

**Issue by sdy623** [tr7zw/NotEnoughAnimations#188]

**Comment by tr7zw** [comment]
No snapshot builds are planned. You can use the closest release and overwrite the Mc version requirement, decent chance that works.

**Comment by tr7zw** [comment]
No not build. You can't build for snapshots without it being setup before. I meant take the 1.20.6 jar from modrinth or cf, and just change the fabric.mod.json to allow loading on 1.21 snapshots.
