### ISSUE TITLE
[Bug] Player arms get glitchy and missing when game's focus lost

### ISSUE THREAD

**Issue by NaiNonTH** [tr7zw/NotEnoughAnimations#19]
log ---> https://pastebin.com/8iP7FsZN

After I read through the log, I assumed that it because of arms rendering error.

**Comment by NaiNonTH** [comment]
* Nevermind, I'm dumb *

**Comment by tr7zw** [comment]
Looks like you used an outdated TRansliterationLib?

**Comment by NaiNonTH** [comment]
> Looks like you used an outdated TRansliterationLib?

Yes, I realized after I submit this issue :(
