### ISSUE TITLE
Feature Request: Some animations for stuff like mining, fishing ect.

### ISSUE THREAD

**Issue by mattmoparkour** [tr7zw/NotEnoughAnimations#193]
might be nice to see some better animations for things such as mining, fishing ect.

**Comment by tr7zw** [comment]
That's not really the focus of this mod. Fishing maybe, as it is kinda weird that it has 0 animations, but that's already tracked at #179 . There are no plans to modify vanilla animations like running/walking/mining etc. For that, I'd recommend stuff like https://modrinth.com/resourcepack/tras-fresh-player .
