### ISSUE TITLE
strange bow placement (bug??? or is my player thug????)

### ISSUE THREAD

**Issue by carbage14** [tr7zw/NotEnoughAnimations#195]
my playermodel, when pulling back the bow, holds the bow at a strange angle compared to the upright position in vanilla. i checked for conflicts and it's the mod causing this odd bow placement.

![image](https://github.com/tr7zw/NotEnoughAnimations/assets/172576427/e86ed71a-7738-4fe8-b489-6b036bc74787)

**Comment by tr7zw** [comment]
Thats the alternative bow animation for Firstperson users, so the bow doesn't clip into the camera. You can change it in the settings.

**Comment by carbage14** [comment]
ah ok
