### ISSUE TITLE
[Suggestion] Would love to config which item can be held to

### ISSUE THREAD

**Issue by Sushikee** [tr7zw/NotEnoughAnimations#196]
I would love to disable lantern and soul lantern from item can be held to

**Comment by tr7zw** [comment]
Thats in the config file. Just remove them there, making sure the json stays valid.

**Comment by Sushikee** [comment]
I tried to remove it from the dev\tr7zw\notenoughanimations\versionless\config but it didnt work. Is there a preffered way to remove both lantern and soul lantern?

![Screenshot 2024-07-18 105324](https://github.com/user-attachments/assets/7b281e18-ceef-42da-a200-1e76bf3e3dbd)
