### ISSUE TITLE
[Problem] Fail to remove certain item in config file

### ISSUE THREAD

**Issue by Sushikee** [tr7zw/NotEnoughAnimations#197]
I tried many times to remove it from the dev\tr7zw\notenoughanimations\versionless\config but it didnt work. Is there a preferred way to remove both lantern and soul lantern?

![Screenshot 2024-07-18 105324](https://github.com/user-attachments/assets/da5c55ba-5d31-4723-be8c-6863ead09af1)

**Comment by tr7zw** [comment]
The config file in the config folder. Not opening the config class in notepad xD.
