### ISSUE TITLE
Could use an animation for paddling boats

### ISSUE THREAD

**Issue by FewerFlaws** [tr7zw/NotEnoughAnimations#2]
Right now a guy just sits there watching the magic happen =P

**Comment by tr7zw** [comment]
Good point

**Comment by tr7zw** [comment]
Actually riding a horse or pig could be put in here too?

**Comment by FewerFlaws** [comment]
Yep, though boats are a priority IMO because the paddles obviously move on their own.  Horses might be tricky due to the reins =]

**Comment by tr7zw** [comment]
This is already on CurseForge :) I later also fixed beds(stop moving the arms/put away the items in the hand), but that's not on there yet.
