### ISSUE TITLE
Empty hands in "holding" position when the holdingItems list has a modded item.

### ISSUE THREAD

**Issue by majikdev** [tr7zw/NotEnoughAnimations#20]
When I add a modded item to the holdingItems list in the config file (tried adding realistic torches torch to it), all empty hands are held up like they are holding a compass or a torch. Verson 1.2.3
![image](https://user-images.githubusercontent.com/45976016/113514939-17a26700-957a-11eb-9a70-431b7cc3b549.png)

**Comment by tr7zw** [comment]
I think adding an invalid item(from a mod that is not loaded) to the list parses to air. I'll fix this next release.

**Comment by tr7zw** [comment]
Fixed in next release.
