### ISSUE TITLE
Missing Item In Hand

### ISSUE THREAD

**Issue by NukolLodda** [tr7zw/NotEnoughAnimations#200]
There exists a bug that seems to occur whenever you place items or some other thing where the item the player is holding disappears in third person pov. I'm not too sure whether this is an incompatibility between the mod First-Person Model or if it's a problem with this mod's code itself but I just wanted to report this   ##problem.
![2024-07-24_13 55 43](https://github.com/user-attachments/assets/d1671e5d-c762-450c-97be-007cc75bb474)

**Comment by tr7zw** [comment]
I don't think this is related to either first person or not enough animations, as this would be reported way more then, and I haven't seen it myself. What's the Mc version, other mods, etc.

**Comment by NukolLodda** [comment]
I'm afraid I don't remember the other mods on the modpack but I do know this is from Minecraft version 1.21, I'll go check later on what the other mods were but this is all I can say for now.

**Comment by NukolLodda** [comment]
So this is the list I can get:

<li><a href="https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar">Detail Armor Bar [Fabric] (by RedLime)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/variant-crafting-tables-fabric">Variant Crafting Tables [Fabric] (by XanthianZ)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/soul-fire-d">Soul fire'd (by CrystalSpider)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/architectury-api">Architectury API (Fabric/Forge/NeoForge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/wider-ender-chests">Wider Ender Chests (by Lupin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks-fabric">YUNG's Menu Tweaks (Fabric) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/resourceful-lib">Resourceful Lib (by ThatGravyBoat)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/grind-enchantments">Grind Enchantments (by mschae23)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric">FTB Library (Fabric) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire">No Hostiles Around Campfire (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/modernfix">ModernFix (by embeddedt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabric-api">Fabric API (by modmuss50)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/spiders-produce-webs">Spiders Produce Webs (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cobweb">Cobweb (by CrystalSpider)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/camp-fires-cook-mobs">Camp Fires Cook Mobs (by supersaiyansubtlety)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easy-anvils">Easy Anvils [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enderpack">EnderPack - New Backpack (by Lupin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/language-reload">Language Reload (by Jerozgen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/balm-fabric">Balm (Fabric Edition) (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mru">M.R.U (by itsmineblock11)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin">Fabric Language Kotlin (by modmuss50)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/paginated-advancements">Paginated Advancements & Custom Frames (by DaFuqsy)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/natures-compass">Nature's Compass (by Chaosyr)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeroplus">XaeroPlus (by CoinRS)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric">Snow! Real Magic! ⛄ (Fabric) (by Snownee)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/first-join-message">First Join Message (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/collective">Collective (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/amplified-nether">Amplified Nether (by Starmute)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric">FTB Teams (Fabric) (by FTB)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric">Better Ping Display [Fabric] (by Quintinity)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/puzzles-lib">Puzzles Lib [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric">Better chunk loading[Forge/Fabric] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice">[FABRIC/QUILT] Disable Custom Worlds Advice (by Nara)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/animal-armor-trims">Animal Armor Trims - Horse & Wolf (by Lupin)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/prism-fabric">Prism [Fabric] (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements">Spyglass Improvements: Zoom, Quick Access... [Fabric/Forge] (by Im_JC52)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/appleskin">AppleSkin (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/make-bubbles-pop">Make Bubbles Pop [Client] [Forge/Fabric/Quilt] (by Tschipcraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config">Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance-fabric">Better Fps - Render Distance[Fabric] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rmes-campfire-leather">RME's Campfire Leather (by RME)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/disable-insecure-chat-toast">Disable Insecure Chat Toast (by NikitaCartes2)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/falling-tree">FallingTree (by rakambda)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tectonic">Tectonic (by Apollo)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/infinity-mending-datapack-mod">Infinity and Mending (by auuruum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fire-arrows-start-fire">Fire Arrows Ignite Fire [Fabric/Forge/NeoForge] (by Mars)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mendable-anvils">Mendable Anvils (by MincraftEinstein)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips-fabric">Legendary Tooltips [Fabric] (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master">YDM's Weapon Master (by YourDailyModderx)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/midnightlib">MidnightLib (by TeamMidnightDust)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/simple-discord-link-bot-forge-fabric-spigot">Simple Discord Link Bot [Forge/Fabric] (by hypherionsa)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep">Just Enough Professions (JEP) (by Mrbysco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker">Better Compatibility Checker (by Gaz_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yacl">YetAnotherConfigLib (by XanderIsDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric">Forge Config API Port (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/netherportalfix-fabric">NetherPortalFix (Fabric Edition) (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d">Skin Layers 3D (Fabric/Forge) (by tr7zw)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/artifacts">Artifacts (by ochotonida)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/comforts">Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/loot-integrations">Loot Integrations[Forge/Fabric] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/visual-workbench">Visual Workbench [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cat_jam">cat_jam (by shmove)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/alternate-current">Alternate Current (by SpaceWalkerRS)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cave-dust">Cave Dust (by LizCannotEven)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/entity-model-features">[EMF] Entity Model Features [Fabric & Forge] (by traben_0)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/torch-hit">Torch hit! (by CrystalSpider)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/craterlib">CraterLib (by hypherionsa)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered">Sound Physics Remastered (by henkelmax)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map">Xaero's World Map (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/blur-fabric">Blur+ (Fabric) (by Motschen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric">Guard Villagers (Fabric/Quilt) (by MrSterner_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pehkui">Pehkui (by Virtuoel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/explorers-compass">Explorer's Compass (by Chaosyr)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/capes">Capes [Fabric/Forge] (by Cael)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/small-ships">Small Ships [Fabric & Forge] (by talhanation)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jade">Jade 🔍 (by Snownee)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/quad">Quad (by LieOnLion)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dynamic-fire-overlay">Dynamic fire overlay (by AndyRussoDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/let-sleeping-dogs-lie-for-fabric">Let Sleeping Dogs Lie (Fabric) (by iChun)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-stats">Better Statistics Screen (by TheCSDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/continuity">Continuity (by Pepper_Bell)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chat-heads">Chat Heads (by dzwdz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/status-effect-bars">Status Effect Bars (by Neecko5b84)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/kiwi-fabric">Kiwi 🥝 (Fabric) (by Snownee)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/searchables">Searchables (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save">Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/glitchcore">GlitchCore (by TheAdubbz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/darkheads">DarkHeads - Player Heads (Fabric/Forge/NeoForge) (by GamerPotion)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/trinkets">Trinkets (Fabric) (by EmilyPloszaj)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/first-person-model">First-person Model (Forge/Fabric) (by tr7zw)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/monolib">MonoLib (by jason13official)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/justenoughbreeding">Just Enough Breeding (JEBr) (by Christofmeg)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cupboard">Cupboard (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/polymorph">Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/faux-custom-entity-data">Faux Custom Entity Data (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/passive-shield">Passive Shield (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/villager-names">Villager Names (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cake-chomps">Cake Chomps (Fabric/Forge/NeoForge/Quilt) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/hearths">Hearths (by bebebea_loste)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/connectivity">Connectivity[Forge/Fabric] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/snow-under-trees-remastered">Snow Under Trees (Fabric)​ (by itsmineblock11)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fast-ip-ping">Fast IP Ping (by Fallen_Breath)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/clumps">Clumps (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric">TerraBlender (Fabric) (by TheAdubbz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-beekeeper-hut-fabric">Friends&Foes - Beekeeper Hut (Fabric/Quilt) (by Faboslav)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/trading-post">Trading Post [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/talkbubbles">TalkBubbles (by Globox_Z)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier">Pick Up Notifier [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/no-chat-reports">No Chat Reports (by Aizistral)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric">[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sulfur-and-potassium-make-more-gunpowder">Sulfur And Potassium - More Gunpowder (by BR4NDER5)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty">Biomes O' Plenty (by Forstride)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/controlling">Controlling (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric">YUNG's API (Fabric) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tcdcommons">TCDCommons API (by TheCSDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap">Xaero's Minimap (by xaero96)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ichunutil">iChunUtil (by iChun)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sit-fabric">Sit (Fabric) (by bl4ckscor3)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/continents">Continents (by Starmute)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/healing-campfire">Healing Campfire (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tschipcrafts-dynamic-lights-mod">Dynamic Lights [Server] [Forge/Fabric/Quilt] (by Tschipcraft)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easyrename">EasyRename (by GravityIO)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat">Simple Voice Chat (by henkelmax)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/carry-on">Carry On (by Tschipp)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/iceberg-fabric">Iceberg [Fabric] (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-flowery-mooblooms-fabric">Friends&Foes - Flowery Mooblooms (Fabric/Quilt) (by Faboslav)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/origins">Origins (Fabric) (by Apace)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric">Eating Animation [Fabric] (by theone_ss)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easy-magic">Easy Magic [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/not-enough-animations">Not Enough Animations (by tr7zw)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tax-free-levels">Tax Free Levels (Fabric/(Neo)Forge) (by Fourmisain)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cut-through">Cut Through (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/true-darkness-fabric">True Darkness Refabricated (by HaXr)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/friends-and-foes">Friends&Foes (Fabric/Quilt) (by Faboslav)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/double-doors">Double Doors (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/armor-statues">Armor Statues [Forge & Fabric] (by Fuzs)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/creativecore">CreativeCore (by CreativeMD)</a></li>

**Comment by tr7zw** [comment]
https://github.com/tr7zw/FirstPersonModel/issues/481#issuecomment-2262819932
