### ISSUE TITLE
(BUG) Newest Update (1.7.4) Makes the Player Invisible.

### ISSUE THREAD

**Issue by TheOtherworldly** [tr7zw/NotEnoughAnimations#201]
I have a custom modpack that I play through the vanilla launcher, so I manually update my mods (I prefer it that way, don't judge me). When I updated this mod to 1.7.4, my player was completely invisible. The only way I could see my player was through the inventory. Even the mod Magic Mirror, which is a mod that displays your player in a mirror, gave me no reflection. 

Upon downgrading the mod, my player model was back to normal. 

Either the new version has a strange bug, or there is a new incompatibility.  
At the same time I updated this mod, I also updated Shoulder Surfing, Immersive Vehicles (I had to downgrade this tho due to another issue), JEI, ModernFix, Xaero's Minimap, Supplementaries, Magic Mirror, Macaw's Lights, Macaw's Doors, DocMod, Security Craft, and Some Assembly Required.

Modloader: Forge 36.2.34
Minecraft Version: 1.16.5
Optifine: Yes

Mod list:
                Optifine
                Eye Mod
		GamingDeco
		Hats+
		TRansliterationLib
		MIMI
		MoreDiscs
		Macaw's Windows
		PlayTics Furniture Mod
		Decoration and furniture mod
		Cooking for Blockheads
		ModernFix
		Sophisticated Backpacks
		V-Tweaks
		Just Enough Resources
		MmmMmmMmmMmm/dummmmmmy
		Chinjufu Mod
		Supplementaries
		Decocraft
		Kacys Cosmetics
		TexelsPaintings
		Nekoration
		Simply Light
		Fairy Lights
		Xerca Mod
		Pam's HarvestCraft 2 Food Extended
		Cluttered
		Curios API
		Vampires Need Umbrellas
		Curious Armor Stands
		Patchouli
		Collective
		Camera Mod
		Flashlight Mod                  
		Random Decorative Things                    
		Better Third Person                    
		Joy of Painting                
		Neon Craft                      
		Custom NPCs         
		Builders Crafts & Addition       
		WorldEdit      
		Eating Animation                  
		Decocraftia                    
		RedWolf Music Mod                     
		MrCrayfish's Furniture Mod           
		Architectury                 
		Macaw's Furniture                    
		Chimes                
		Mine-Pop!                  
		Cloth Config v4 API                  
		Valtiel s Girl Armor Mod               
		Macaw's Lights and Lamps
		Essential             
		Otherworldly's GUI Mod (My mod)
		Better Animations Collection
		AlwaysEat                     
		Documents Mod      
		Pam's HarvestCraft 2 Fruit Trees                    
		Some Assembly Required             
		Locks                   
		VDeco                         
		Just Enough Items               
		Furnish          
		Abnormals Core                    
		Falling Leaves      
		Macaw's Paintings                     
		Configured       
		Lightman's Currency      
		Colt's Cosmetic Armour Mod             
		World Time     
		Online Picture Frame 2                   
		Furniture Frenzy             
		Table Top Craft               
		Mapper Base          
		EmbellishCraft            
		Magic Vibe Decorations                     
		Immersive Vehicles (formerly MTS)                      
		Pool Floatys Mod                    
		Dad's Sewing                       
		Nb_mod                    
		Panorama                    
		Nosiphus Furniture Mod                
		First Aid                     
		Luna's Clothing Mod                     
		forge-1.16.5-36.2.34-universal.jar
		Mo'Blocks                   
		Dynamic Surroundings                  
		VariedCommodities           
		Selene               
		Oaks Decor Backported!                      
		FurbishCraft                    
		forge-1.16.5-36.2.34-client.jar                   
		Dramatic Doors              
		Modernxl                     
		Illuminations           
		Skin Swapper                     
		Shoulder Surfing Reloaded              
		Armor Poser                     
		Pam's HarvestCraft 2 Crops                   
		Natural Decor Mod                     
		Personality                    
		JEI Integration                  
		NotEnoughAnimations Mod                    
		Xaero's Minimap                   
		Star Worm Deco Mod              
		Pam's HarvestCraft 2 Food Core                 
		Diet            
		Time & Wind CT Forge                    
		More Player Models       
		Cycle Paintings                    
		Placeable Items                 
		Keyboard Wizard                 
		AutoRegLib                  
		Quark                
		SecurityCraft                  
		Sit                  
		Searchlight                    
		Immersive Paintings             
		Simply Tea                   
		PlayTics Deco                     
		Ambient Environment                 
		Raven Coffee Mod               
		Neon Craft 2          
		Selfie Cam                    
		Ferrite Core
		ApexCore                
		Fantasy's Furniture                   
		guitar+/MCMusic                   
		Puzzles Lib
		Nef Deco Mod/Nef's Medieval Pub                
		Door Knocker (Forge)          
		XK's Deco                   
		Chisels & bits                   
		Magic Mirror      
		Exline's Furniture             
		Better Foliage 
		Armouror's Workshop  
		OpenBlocks Elevator

**Comment by tr7zw** [comment]
There are no code changes between 1.7.3 and 1.7.4.

**Comment by TheOtherworldly** [comment]
I believe I had a really old version, it was 1.2.4 (this is a manual modpack lol)

**Comment by tr7zw** [comment]
Closing as stale, no further reports of the issue/comments.
