### ISSUE TITLE
Leg animations gets overwritten by animation resource pack

### ISSUE THREAD

**Issue by modyreso20111** [tr7zw/NotEnoughAnimations#203]

**Comment by tr7zw** [comment]
What is detailed animations?

**Comment by modyreso20111** [comment]
It's another animation resource pack

**Comment by tr7zw** [comment]
Then I assume it's up to the packs. Fresh Moves works perfectly fine.

**Comment by modyreso20111** [comment]
Oh ok did yall fix the fresh moves keg problem? Cuz your leg animations don't work with jt

**Comment by tr7zw** [comment]
What leg animations?

**Comment by modyreso20111** [comment]
I suggest y'all add for the not enough animations a resource pack where it contains all the animations so no resource pack overwrites them like how fresh moves' leg animations overwrite your leg animation it's a problem for the whole community who use fresh moves and not enough animations so that might be my problem rn but the detailed animations glitch  I will report it to its owners

**Comment by tr7zw** [comment]
I still have no clue what this issue is about. Not Enough Animations doesn't have any leg animations except when on a ladder and I guess maybe crawling. So I don't really get what Fresh Moves is supposed to be overwriting?

**Comment by modyreso20111** [comment]
I am not trying to ruin your day but it's just that I want to feel both mods without having anything overwritten
