### ISSUE TITLE
Banner shields textures break

### ISSUE THREAD

**Issue by SorathePuffin** [tr7zw/NotEnoughAnimations#204]
With the mod: 
![2024-08-02_19 08 27](https://github.com/user-attachments/assets/adf62a98-4b61-4cc2-bad9-f60518da4636)
(also for some reason the shield that the character in the inventory has does display properly, alongside the item.) 
![2024-08-02_19 08 30](https://github.com/user-attachments/assets/bad0dee7-46eb-425b-9eba-2d6b929ac1e2)

Without the mod: 
![2024-08-02_19 05 41](https://github.com/user-attachments/assets/e044a89c-4b4d-4182-a192-4ac3c8035ca9)

The shield: 
![2024-08-02_19 05 52](https://github.com/user-attachments/assets/163c404d-2a6f-4169-b626-18727833ce1b)

**Comment by tr7zw** [comment]
Afaik this is related to 3d skin layers, not NEA.
