### ISSUE TITLE
Incompatible with Extra Boats Mod.

### ISSUE THREAD

**Issue by Linusintro** [tr7zw/NotEnoughAnimations#208]
This mod doesn't play the boat rowing animation with the boats from the [Extra Boats](https://www.curseforge.com/minecraft/mc-mods/extra-boats) mod. I suggest adding some sort of list for boats that can modified to add a boat rowing animation for modded boats.

**Comment by tr7zw** [comment]
Can't add the boat rowing animation if the mod can't figure out that the player is sitting in a boat. I think for this I'll take the stance like with other modded items, it's the job of the mod devs to add animations to their stuff. This mod is intended to fix missing vanilla animations, not other mods.
