### ISSUE TITLE
Screen tearing effect on player's body when Rotation locking is set to fixed

### ISSUE THREAD

**Issue by lowerpolygons** [tr7zw/NotEnoughAnimations#210]
what the tittle says, when rotation type is set to fixed the character shakes as it moves from either side to side or when climbing up a ladder. The effect is even more present when looking around while climbing up causing even more abrupt tearing

only other mod present is First Person Model, playing on 1.21.1 

https://github.com/user-attachments/assets/666e7c10-2e7f-4842-b918-61eafee9553d

**Comment by tr7zw** [comment]
That's not screen tearing. That's the frame dalta causing issues.

**Comment by lowerpolygons** [comment]
> That's not screen tearing. That's the frame dalta causing issues.

thank you for the reply, I used screen tearing to sort of describe what it looks like. As an animator myself it does seem to be related to the players body trying to display two frames of animation at the same time which causes the "flickering" but I'm unaware of why it's doing this, no other mods are trying to animate the player so, what could it be? I like playing with the players body locked in place instead of it rotating to the sides when walking, which causes me motion sickness
