### ISSUE TITLE
Map does not render correctly in 1.19.2

### ISSUE THREAD

**Issue by Vinzound** [tr7zw/NotEnoughAnimations#211]
In the most recent version of this mod (1.7.5) the map in the player's hand does not render correctly and looks strange when playing on 1.19.2.

I understand that it is an old version of Minecraft, but I would really appreciate it if you fixed it for those who still play this version :')

**Comment by tr7zw** [comment]
Duplicate #210

**Comment by Vinzound** [comment]
Actually, the problem is still present, at least in 1.19.2 :(
![image](https://github.com/user-attachments/assets/73eff259-c9a6-45dd-b448-f5540de63258)

**Comment by Deepfriedyag** [comment]
im on 1.16.5 and this bug is present without shaders, anyone know the fix?
