### ISSUE TITLE
Map Flickering on 1.7.5-1.20.4 - Fabric

### ISSUE THREAD

**Issue by vMelioz** [tr7zw/NotEnoughAnimations#212]
I added the mod to my modpack with 70+ mods and noticed that the map wasn't rendering properly. I thought that maybe the resource pack was the problem, so I disabled it, but nothing changed. Next, I tried disabling other mods, but the map still wasn't rendering properly. I then created a completely new Minecraft instance in Prism Launcher, downloaded only Fabric API and Not Enough Animations, but the map was still flickering. Finally, I tried downloading an older version of the mod (1.7.4 for 1.20.4), and that fixed the problem.

fabric 1.20.4
gtx 1660ti
ryzen 5 3600x

https://github.com/user-attachments/assets/4de4a409-28c7-487c-98f3-03a6a93095c9

https://github.com/user-attachments/assets/d9957139-0604-486c-8ac1-95bbdab8af3e

**Comment by tr7zw** [comment]
Duplicate #210

**Comment by Deepfriedyag** [comment]
> Duplicate #210

So how do you fix it? in the original thread I can't see the solution for this?

**Comment by tr7zw** [comment]
Duplicate does not mean fixed. Nothing about the code changed, so haven't had time to look into why this happens.

**Comment by Deepfriedyag** [comment]
> Duplicate does not mean fixed. Nothing about the code changed, so haven't had time to look into why this happens.

Alright, I will post the solution to this bug here because I am really smart and nobody seems to have figured it out in 2 different github repos:

To fix this, you have to downgrade the "Not Enough Animations" version. On 1.16.5, downgrading it from 1.7.5 to 1.7.4 completely fixed this for me. The beta version 1.7.5 (and most likely up) is faulty and has this bug.

**Comment by tr7zw** [comment]
People mentioned that already on the other issze. As I said, there has been no code change between these 2 versions. So why it's suddenly broken is not clear and hasn't been debugged yet.
