### ISSUE TITLE
Hold Up Animation -> items become invisible

### ISSUE THREAD

**Issue by QwertRvg** [tr7zw/NotEnoughAnimations#215]
Fabric 1.20.1
When the Hold Up Animation option is enabled, the held item becomes invisible in third person after a few seconds.
So when viewing another player or yourself in third person, it looks as if the player is holding nothing.
![image](https://github.com/user-attachments/assets/efc356a9-f11d-42db-bdb2-a0e562e0ad99)

**Comment by tr7zw** [comment]
The holdup animation just rotates the arm, it can't hide the held item. Seeing as no one else reported such an issue, I assume you have some incompatible or broken mod installed.

**Comment by QwertRvg** [comment]
it does not happen when the option is disabled, must be an incompatiblity then yeah
ill look into what mod it might be
thanks

**Comment by tr7zw** [comment]
Closing this as stale, no other reports of this issue/comments.
