### ISSUE TITLE
Add api

### ISSUE THREAD

**Issue by RazorPlay01** [tr7zw/NotEnoughAnimations#217]
Hello again on this occasion again doing tests with my mod which modifies the vanilla animations using player animator to make my mod compatible with this I have required to make mixin to the classes of your animations because for example if I want to play your animation kiero q running as naruto require q disable the animations of the arms in my mod that case I have already done it and it works well but I found a problem when for example do the same with the animations of the bow in the same way I must disable the arms in my mod but there is an error in the mixin Method signature does not match expected signature. I have done and it works fine but I have found a problem when for example to do the same with the bow animations that in the same way I must disable the braces but there is an error in the mixin Method signature does not match expected signature for Inject something that does not happen with the animation in the mixin of the naruto animation and then I make intellij to fix this error and it generates me this

![carbon](https://github.com/user-attachments/assets/f47edf86-e9df-4c4a-869e-5ae377ab4ac3)

I leave you in passing the example with the class it injects to the naruto animation.

![carbon (1)](https://github.com/user-attachments/assets/b09438f5-f466-469f-8d2c-5c292d4e094e)

It's some kind of error with the mapping but I really don't understand how to fix it.
Pd: I am using mojang mapping for my mod.

**Comment by tr7zw** [comment]
Hm, I think it would be simpler to just define a quick api that mods can on the fly disable animations. The other (initially intended) version would be, that you just also register an animation with a higher priority(probably around the level of the vanilla animations) to just overwrite my animations with yours.

**Comment by RazorPlay01** [comment]
Yes, I am in the process of creating an api that will allow other modders to modify the activation and deactivation of the animations for each body part separately if they like it, I just came across this problem and found it extremely curious.
Thanks for your help

**Comment by tr7zw** [comment]
As in a PR? I'll soon work on NEA for the 1.21.3 update, so I could quickly throw together an API package to allow registering custom animations correctly and to allow filtering or animation classes. Mixing into stuff like the NarutoRunning isn't the way to go I think.

**Comment by RazorPlay01** [comment]
I was referring to my mod so that other devs could undo my animations but yes it would be good what you suggest.
Mixins are never the best choice anyway hahahahahaha

**Comment by tr7zw** [comment]
Then consider it done with the next release in the next 7-ish days (currently busy with irl stuff, and can't release new versions because Forge is still not on 1.21.3).

**Comment by RazorPlay01** [comment]
Ok, thanks again for the help.
