### ISSUE TITLE
Second skin layer not following animations

### ISSUE THREAD

**Issue by wiisafetymanual** [tr7zw/NotEnoughAnimations#220]
When the mods animations play, only the first skin layer does them. The second skin layer uses the vanilla animations. Also, even when not playing any animations from the mod, the second skin layer plays animations at a slower speed, which makes it lag behind the first skin layer while running

Minecraft 1.20.1
Forge 47.3.11
Mod Version 1.8.0

**Comment by tr7zw** [comment]
Hm looks like due to a change of 1.21.3 some logic made its way into older versions (I blame @viciscat /s), I'll fix it later today.

**Comment by DracoHero** [comment]
I have the same problem in that same version of Forge (47.3.12), in Minecraft 1.20.1
