### ISSUE TITLE
Animation Smoothing causes the second layer to detach.

### ISSUE THREAD

**Issue by iFlameWaterYT** [tr7zw/NotEnoughAnimations#222]
If Figura is installed, the vanilla player model is visible and Animation Smoothing is turned on, the second layer will end up using the vanilla animations of the game rather than the mod animations, causing them to detach while walking, mining/punching, selecting NEA config defined items (torches, maps, etc), or while sleeping with an item in hand.

https://github.com/user-attachments/assets/e620628a-2beb-4b48-adbd-5860f9fbc9ee

**Comment by tr7zw** [comment]
Update the mod, this is fixed already.

**Comment by tr7zw** [comment]
Looking at #185 , possible that Figura in general doesn't work right since it replaces the player rendering.

**Comment by iFlameWaterYT** [comment]
> Update the mod, this is fixed already. (at least for vanilla, otherwise, it's a Figura issue probably/just not compatible).

Oh sorry, I didn't see that a new version released, I already tested it and is fixed also for Figura.

**Comment by tr7zw** [comment]
Then it was the vanilla issue. 1.21.3 connected arm and layer, and this logic accidentally bled back into old versions where this is not yet the case.

**Comment by iFlameWaterYT** [comment]
> Then it was the vanilla issue. 1.21.3 connected arm and layer, and this logic accidentally bled back into old versions where this is not yet the case.

I guess it was, the weird thing about it was that it started happening to me as soon as I installed Figura and idk why. But now it's fixed, thank you btw.
