### ISSUE TITLE
The game crashes when opening the configuration interface

### ISSUE THREAD

**Issue by scarls686** [tr7zw/NotEnoughAnimations#228]
MOD version:notenoughanimations-forge-1.8.1-mc1.18.2
Forge version:40.2.9

**Comment by tr7zw** [comment]
Next time please add the crash log. Seems to be some issue with the hovertext which is odd, since nothing changed for literal years on 1.18.2, and FirstPerson mod using the same config screen doesn't have this issue 🤔

**Comment by tr7zw** [comment]
Ok, added a workaround for this weird behavior. Not sure how this is possible, as it doesn't happen on Fabric or other mods on Forge with the same codebase.
