### ISSUE TITLE
[Compatibility Request/Bug Report] Dual Riders view issues

### ISSUE THREAD

**Issue by Abbanon** [tr7zw/NotEnoughAnimations#25]
Currently, when using this mod alongside Dual Riders (https://www.curseforge.com/minecraft/mc-mods/dual-riders), the person sitting in the back also moves their arms as if they're controlling the reins, and holds their arms forward too.

It causes severe visual clipping to the person sitting in front, particularly when the person in back is holding large items such as shields and tools:
![2021-05-18_13 13 39](https://user-images.githubusercontent.com/37251822/118696037-db4e6180-b7db-11eb-94bd-443a2d0769d9.png)

Would you have any consideration for resolving this, if at all possible?
Further information: Fabric, 1.16.5, latest mod version and dependencies.

**Comment by tr7zw** [comment]
Hm not sure how this could be resolved. I guess the first person getting on the horse is the person in front? I'll have to look into how this can be fixed.

**Comment by JSBOfficial** [comment]
Maybe make the back rider invisible when the personal sitting in front is in first person view.

**Comment by tr7zw** [comment]
The arms being in front is the same issue as with boats(both players row the boat). So the animation needs a check that only the "main" passenger gets animations applied.

**Comment by tr7zw** [comment]
This got fixed, only the front person is now doing the boat/horse animation.
