### ISSUE TITLE
Arms Always Outstretched

### ISSUE THREAD

**Issue by SaltSouls** [tr7zw/NotEnoughAnimations#26]
With the Personality mod installed, if you save while in the sitting animation and then come back into the world and stand up, your arms will be locked into the sitting animation position. The biggest problem with this is that no amount of saving and quitting or creating new worlds will fix it as it seems to persist across all worlds.

**Comment by tr7zw** [comment]
I haven't had any report of something like this since, and more or less rewrote the smoothing logic. Gonna assume its gone.
