### ISSUE TITLE
[1.16.5 Forge] The trident is held backwards

### ISSUE THREAD

**Issue by V972** [tr7zw/NotEnoughAnimations#27]
Forge 36.1.15
Not Enough Animations 1.2.4
TRansliterationLib 1.0.4
_Shoulder Surfing 2.0.6 (If needed)_

The trident is helf backwards (both in 3rd and 1st person view, will make separate issue in the FirstPersonModel github)

3rd person
![image](https://user-images.githubusercontent.com/45125685/121498112-c7fe7280-c9e4-11eb-87ed-f9d6c362f76a.png)

1st person
![image](https://user-images.githubusercontent.com/45125685/121498173-d64c8e80-c9e4-11eb-8883-978e89d471e7.png)

**Comment by V972** [comment]
Forgot to mention: it's backwards only when the player is charging it to throw, just idle holding it in the hand is normal.

![image](https://user-images.githubusercontent.com/45125685/121498655-4b1fc880-c9e5-11eb-9bf4-cfab650b44de.png)

**Comment by tr7zw** [comment]
Haven't heard anything about this outside of this one case, probably was some mod compatibility issue that is hopefully resolved. Reopen this issue if this is reproduced in some way.
