### ISSUE TITLE
[1.16.5 Forge] modded items are ignored in holdingItems config

### ISSUE THREAD

**Issue by V972** [tr7zw/NotEnoughAnimations#28]
Forge 36.1.15
Not Enough Animations 1.2.4
TRansliterationLib 1.0.4

I added several new items from vanilla and mods, namely modded torches, lanterns and compasses (but not only them).
Vanilla items work, but modded ones don't.

Here's the full list:
```
  "holdingItems": [
    "minecraft:clock",
    "minecraft:compass",
    "minecraft:torch",
    "minecraft:lantern",
	"minecraft:soul_torch",
	"minecraft:soul_lantern",
	"infernalexp:lantern_glow",
	"endergetic:ender_torch",
	"endergetic:ender_lantern",
	"sereneseasons:calendar",
	"adpother:aerometer",
	"naturescompass:naturescompass",
	"structurescompass:structures_compass"
  ],
```

Torches:
![image](https://user-images.githubusercontent.com/45125685/121517555-30a31a80-c9f8-11eb-96ba-8ad0bf1a133e.png)
![image](https://user-images.githubusercontent.com/45125685/121517529-284adf80-c9f8-11eb-9f8e-5d71f4157523.png)

Compasses:
![image](https://user-images.githubusercontent.com/45125685/121517303-e02bbd00-c9f7-11eb-984e-21ddedb99296.png)

Misc. items:
![image](https://user-images.githubusercontent.com/45125685/121517479-15d0a600-c9f8-11eb-94bc-98bdc12d3053.png)

**Comment by tr7zw** [comment]
Hm this issue seems to have flown under my radar, I guess it's an issue with when the itemlist is generated(basically before the items are loaded in by the other mods). Will fix this in the next version.
