### ISSUE TITLE
Animation is way too sloppy

### ISSUE THREAD

**Issue by CalXee** [tr7zw/NotEnoughAnimations#29]
I get this mod is trying to smooth the animations, but there is a reason why the vanilla game hasn't done that yet.

The vanilla animation, while with no smooth transitions at all, looks crisp in pvp scenarios, while with this mod installed, it looks slow and sloppy, and all around a bit off putting.

I think the transition animation needs to move way faster, the current speed feels like the speed of players moving while under mining fatigue.

**Comment by tr7zw** [comment]
You can change the speed to your liking in the config(or turn it off in general). There is no simple definitive speed between pvp players and normal survival/modded/roleplay/builders.
