### ISSUE TITLE
[Suggestion] ladder climbing animation

### ISSUE THREAD

**Issue by RyanCR03** [tr7zw/NotEnoughAnimations#3]
it looks very odd having the player magically fly up with the power of sticks placed in the right order...

**Comment by RyanCR03** [comment]
i made something to what it could look like [https://im4.ezgif.com/tmp/ezgif-4-b35b9ee73e6a.gif](image)

**Comment by tr7zw** [comment]
Yea that's doable I guess. But you have to kinda remember that you can rotate on the ladder so it might also look really stupid with people climbing a ladder backward 😅

**Comment by RyanCR03** [comment]
it already does

**Comment by RyanCR03** [comment]
i thought of an idea where you would be able to move your head freely in first person but in third person your head would stop moving after 45 degrees from your back and then once the player moves their head beyond their back their head kinda snaps to a different 45 degrees from their back and be able to move their head freely in one direction but not the other in third person... I'm not good at explaining things.

**Comment by RyanCR03** [comment]
![image](https://i.imgur.com/0YPpefv.gif)

**Comment by tr7zw** [comment]
I'll have to test how well you can identify what climbable block you're on. Since there are ladders, vines, the nether tree things.

**Comment by RyanCR03** [comment]
the nether vines would make the most sense just having the walking animation

**Comment by CalXee** [comment]
https://youtu.be/nYKOTRvuE6o

**Comment by tr7zw** [comment]
Ok this is now actually fully implemented in the current rewrite branch. With locking to the ladder, limiting the head rotation and the arms being a bit higher than in the current version. Also won't start the animation while still touching the ground.
