### ISSUE TITLE
[Bug] calling for wrong dependency 1.17

### ISSUE THREAD

**Issue by SylisMC** [tr7zw/NotEnoughAnimations#34]
Im not sure if the problem is because of FirstPersonMod or Not Enough Animations but on curseforge, when downloading FirstPersonMod it calls for Not Enough Animations and **TRansliterationLib-1.0.4.jar (1.16)**

I created this  FPM's github https://github.com/tr7zw/FirstPersonModel/issues/221

**Comment by tr7zw** [comment]
Tracking over at FPM
