### ISSUE TITLE
Hand animation does not shown, paperdoll only.

### ISSUE THREAD

**Issue by L0oois** [tr7zw/NotEnoughAnimations#35]
I have both mods "first person model" and "NotEnoughAnimation". When using the "paper doll" option only enabled without the "model rendering" in the first person view, the arm animation is not displayed, unless you have the first hand and the second hand full.

https://user-images.githubusercontent.com/87247529/130374222-c83de9db-1639-46df-9800-d7c3348cc4d9.mp4

**Comment by L0oois** [comment]
Fabric 1.17.1
-NotEnoughAnimation 1.3.0
-First Peson Model Mod 2.0.2

**Comment by tr7zw** [comment]
Duplicate https://github.com/tr7zw/FirstPersonModel/issues/125
