### ISSUE TITLE
[Idea] Change position of where a lantern is hold

### ISSUE THREAD

**Issue by Andre601** [tr7zw/NotEnoughAnimations#38]
Not sure if that can/should be done by this mod, or if it should better be done through a resource pack, but I feel like it could look better and cooler if the player model would hold the (soul) lantern at the top section, similar to how you would usually do with actual lanterns.

**Comment by tr7zw** [comment]
I think it would be better to use a resource pack that turns the item into a 3d model and then shifts it to under the arm. But I'm not that good in creating these kinds of resource packs, would need to ask around.

**Comment by Andre601** [comment]
> I think it would be better to use a resource pack that turns the item into a 3d model and then shifts it to under the arm. But I'm not that good in creating these kinds of resource packs, would need to ask around.

There is VanillaTweaks that has an option to render specific items - including the lantern - as 3D in the inventory.
Thing is, that the position of the lamp sadly isn't changed and it's similar to any normal block, making it look stupid with the first person mod and this one active...
Will give them feedback on this. Maybe they add an option to make the lamp be positioned differently...

**Comment by tr7zw** [comment]
Having this in vanilla tweaks would be really cool.
