### ISSUE TITLE
Game Crashed after joining the world

### ISSUE THREAD

**Issue by NaiNonTH** [tr7zw/NotEnoughAnimations#40]
[crash-2021-10-01_20.54.15-client.txt](https://github.com/tr7zw/NotEnoughAnimations/files/7267704/crash-2021-10-01_20.54.15-client.txt)

**Comment by tr7zw** [comment]
Fixed with the 1.2.2 release of TRansliterationlib(I fucked up Vec3d and Vector3d while moving from yarn to mojmap)

**Comment by NaiNonTH** [comment]
ok lmao
