### ISSUE TITLE
Game crash when sneaking+climbing

### ISSUE THREAD

**Issue by AlexProGear** [tr7zw/NotEnoughAnimations#41]
If you force yourself into sneaking state (via slabs) and walk near anything climbable the game crashes
Link to the crash report: https://pastebin.com/j9DhBuVb
Here's a setup to test – just sneak in between slabs and walk towards ladder
![2021-10-01_20 31 52](https://user-images.githubusercontent.com/41666982/135647377-d6e251a6-2bfc-45f3-b414-7ef8e378a35c.png)

**Comment by tr7zw** [comment]
Fixed with the 1.2.2 release of TRansliterationlib(I fucked up Vec3d and Vector3d while moving from yarn to mojmap)
