### ISSUE TITLE
[Bug] Having an item in your offhand with your fist in your main hand freeze's your arms on the paper doll.

### ISSUE THREAD

**Issue by CasualWolfGamer** [tr7zw/NotEnoughAnimations#51]
Similar to the previous issue where your arms were frozen on paperdoll, Your main hand will freeze if you have an item in your offhand but it unfreezes only if you go in third person. Otherwise, going back to first person, it freezes.

**Comment by tr7zw** [comment]
That was fixed in the latest release. Please check your version(and remember to update TRansliteration lib at the same time, else it won't work).

**Comment by tr7zw** [comment]
This had been resolved for some time.
