### ISSUE TITLE
1.4.0 incompatible with Essential

### ISSUE THREAD

**Issue by srnyx** [tr7zw/NotEnoughAnimations#54]
When using 1.4.0, all entities are invisible and the [Essential](https://essential.gg/) stuff is broken (buttons and stuff).

**Comment by tr7zw** [comment]
Why the heck is anything called essentials other than the plugin?!? Is it on curse/open source?

**Comment by srnyx** [comment]
> Is it on curse

No

> modrinth

No

> open source?

No

**Comment by tr7zw** [comment]
Then probably won't sink time into it currently. Maybe sometime later.

**Comment by karmette** [comment]
Essential is a quality of life mod made by Sk1erLLC. It features things such as cosmetics, account switcher, zoom, and friends system. Go to https://essential.gg/ to learn more.

And yes its incompatible please fix :[

**Comment by srnyx** [comment]
Essential team is gonna look into it

**Comment by karmette** [comment]
ok cool. also scratch the Sk1erLLC its actually ModCore

**Comment by srnyx** [comment]
> ok cool. also scratch the Sk1erLLC its actually ModCore

I think Sk1erLLC manages/made ModCore & Essentials

**Comment by srnyx** [comment]
Essential has fixed this on their side.
