### ISSUE TITLE
2nd head layer messes up with ladder climbing animation in front f5

### ISSUE THREAD

**Issue by GalaxysWithFiles** [tr7zw/NotEnoughAnimations#56]
![image](https://user-images.githubusercontent.com/95949301/145661322-e82a3021-d87d-40aa-af06-1decc11d5632.png)

**Comment by tr7zw** [comment]
Ah crap right, this is with 3d skin layers, I know I forgot something. Thanks for the issue.

**Comment by tr7zw** [comment]
Seems to be fixed with the newest 3d Skin Layers version.

**Comment by tr7zw** [comment]
I did try that with the newest versions on curse and it worked for me?
![](https://tr7zw.dev/u/1646060678.png)
