### ISSUE TITLE
Possible 1.4.0 for 1.16.5?

### ISSUE THREAD

**Issue by IdrisQe** [tr7zw/NotEnoughAnimations#57]
1.3.0 and 1.4.0 resolved a lot of issues and added some new stuff that would be really nice (crawling animation in particular to use alongside First Person Model) but it isn't available on 1.16.5, which a lot of good modpacks are still stuck on for the time being.

I hate to be "that guy" but would it be too much work to do a 1.16.5 port of the update?
I fully understand if not, just thought I'd ask and see-

**Comment by tr7zw** [comment]
Internally the new versions are basically entire recodes, also using different mappings(it's the reason TRansliterationLib is not required anymore). So backporting to 1.16 would be a lot of work, while it still has a usable (legacy) version, and is now outdated by 2 major releases(I usually only go back 1 release). I know Forge modpacks lag behind a lot, but I think it should be fine to just have the old versions for now, while giving a grace period of ~6-12+ months to update.

**Comment by IdrisQe** [comment]
That's a fair response! Thanks for the explanation though

**Comment by tr7zw** [comment]
The issue is that this has the potential to quickly get exponentially become more work. I mean would I update 1.15/1.14 still? Where to draw the line? So think the 2 latest versions is a fair deal, with how often Mojang releases new versions.
