### ISSUE TITLE
[Feature request] Toggle for singular back item (as opposed to two duplicates)

### ISSUE THREAD

**Issue by ShaneTRS** [tr7zw/NotEnoughAnimations#60]
Relevant line: https://github.com/tr7zw/NotEnoughAnimations/blob/1.17/NEAShared/src/main/java/dev/tr7zw/notenoughanimations/renderlayer/BackItemsRenderLayer.java#L74

**Comment by tr7zw** [comment]
Noteworthy that this feature is disabled by default and marked as WIP(Work in progress). So yes it's planned to not work like it does right now.

**Comment by tr7zw** [comment]
I've decided to remove this unfished feature again, since this is not the direction this mod should be heading. Therefore gonna close related issues.
