### ISSUE TITLE
Not enough animations doesnt work

### ISSUE THREAD

**Issue by juancruz050** [tr7zw/NotEnoughAnimations#61]
When i enter my world, there arent any animations, I do have the other mod to make this mod work, but it still doesnt work

**Comment by tr7zw** [comment]
Uhm, are you sure the mod is loaded(visible in the ingame mod list), are the animations enabled in the settings and for which animation did you look out for? Also no, FirstPerson Mod is not required.

**Comment by juancruz050** [comment]
ill check that after my vacations

**Comment by tr7zw** [comment]
*bumb*
