### ISSUE TITLE
Disable Scabbard Sword in config automatically when Backslot is installed

### ISSUE THREAD

**Issue by Alkiasan** [tr7zw/NotEnoughAnimations#62]
Scabbard Sword interacts quite weirdly with Backslot whilst it's installed, if possible, can you have NEA auto-disable Scabbord Sword when Backslot is installed?
Seen in issue report here:
https://github.com/Globox1997/BackSlot/issues/51

**Comment by tr7zw** [comment]
Yea I can look into that later, for now just disable the Scabbard feature in the settings/config.

**Comment by Alkiasan** [comment]
Thanks! It mostly effects multiplayer as it's quite inconvenent to remind players to disable it in config, since it appears to be a clientside option
