### ISSUE TITLE
[Issue, Forge 1.16.5] Mod Causing Crash on Loading World

### ISSUE THREAD

**Issue by VideoGames1000** [tr7zw/NotEnoughAnimations#65]
Mods Used:
Forge Modloader v 32.6.0
FirstPersonMod v 2.0.0
notenoughanimations v 1.2.3
TRansliterationLib v 1.0.3

Game hardcrashes when loading into a world, have isolated it to this mod specifically. A brief glance at the logs suggests something to do with crossbows and arm rendering being the source of the problem?

The sooner this can be looked into the better, as the additional features of this mod would be very nice to have.

Crash Log: https://pastebin.com/yHduDBpq

**Comment by tr7zw** [comment]
Eh that's a looong outdated version? And for that version TRansliterationLib(not maintained anymore) is outdated/the wrong version.

**Comment by VideoGames1000** [comment]
Ah, that's just the versions that showed up when I installed the mod through AT Launcher. What version(s) of the mod(s) should I be installing for proper functioning then?

**Comment by tr7zw** [comment]
Well 1.16 Not enough Animations is 1.2.4 and should require the TRansliterationLib 1.0.4(the latest version), and for FirstPersonMod 2.0.1. No clue where ATLauncher gets these versions from, but for example, the TRansliteration lib update is from March last year.
