### ISSUE TITLE
[Compatibility Request/Bug Report] Origins´s translucent skins dont work with 3D Layers

### ISSUE THREAD

**Issue by Diego13303** [tr7zw/NotEnoughAnimations#67]
Powers that change the hue or opacity of your skin don´t affect 3D layers at all. Could this be fixed...?
![2022-02-21_21 25 46](https://user-images.githubusercontent.com/91715852/155051728-94e13a8e-7d44-45c2-8989-af9e4bd3d6e5.png)
![2022-02-21_21 27 45](https://user-images.githubusercontent.com/91715852/155051895-ba0a3c9f-749c-497e-a2e1-bf78928c139a.png)

**Comment by tr7zw** [comment]
https://github.com/tr7zw/3d-Skin-Layers/issues/36 tracked here.
