### ISSUE TITLE
Smoother animation for sitting/standing

### ISSUE THREAD

**Issue by muzikbike** [tr7zw/NotEnoughAnimations#69]
Similarly to #52, the transitions between "sitting" and "standing" states are still immediate, and not smoothed like many other animations are. It might be a good idea to have a more continuous transition here as well.
![2022-02-28_14 33 01](https://user-images.githubusercontent.com/52297970/156001312-3065b742-777e-4f93-b98b-3cf3f2d65713.png)
![2022-02-28_14 33 01_2](https://user-images.githubusercontent.com/52297970/156001314-28cc353e-cbc4-466f-a23f-7990c54de122.png)

**Comment by tr7zw** [comment]
Hm I could look into that, one issue is that this just is a flag whether the model is sitting or not, so might be more tricky than expected.

**Comment by tr7zw** [comment]
I did enable the smoothing from the arms to the legs too, so there is a really short blend when getting up. Not sure how much more can be done, since it does teleport the player and rotates him 90°(same with bed).
