### ISSUE TITLE
[Suggestion] Less aggressive item swinging

### ISSUE THREAD

**Issue by TheRealSpeedy** [tr7zw/NotEnoughAnimations#7]
Heyho,

would it be possible to implement a less agressive item swinging (pickaxe, sword, etc.)?
Especially when using the first-person Model mod, the aggressive swinging gives me anxiety.

**Comment by tr7zw** [comment]
I mean what would you see as "less aggressively"? You are by definition hitting stuff with the item in your hand, so other than adding different animations when using an axe/pickaxe/sword to be better fitting, I don't see how you could "less aggressively" hit a tree with your bare hands 😅

**Comment by TheRealSpeedy** [comment]
> I mean what would you see as "less aggressively"? You are by definition hitting stuff with the item in your hand, so other than adding different animations when using an axe/pickaxe/sword to be better fitting, I don't see how you could "less aggressively" hit a tree with your bare hands 😅

The vanilla animation of swinging you pickaxe is "first, I ram it into my eye socket, then into my knee". Same as the sword animation, you always cut your ear off when swinging a sword.

By "less aggressive" I really mean "less exaggerated".

**Comment by tr7zw** [comment]
I could look into that. Like I said Pickaxe/Axe etc are definitely changeable, and making some other animations feel more natural probably wouldn't hurt too.

**Comment by TheRealSpeedy** [comment]
I'm looking forward to see your new animations one day 😊
