### ISSUE TITLE
"Punching" animation while crawling snaps back immediately instead of smoothly

### ISSUE THREAD

**Issue by muzikbike** [tr7zw/NotEnoughAnimations#72]
Usually when standing or sneaking, the punch/item use animation results in the arm smoothly reverting to its default position. This doesn't seem to happen when crawling (yet to test if this is a vanilla issue or a problem with the crawling animation the mod adds), in which the arm immediately shifts back to its default position rather than smoothly going back.
![crawlinganim-discontinuity](https://user-images.githubusercontent.com/52297970/156018414-8e93a2d6-35ec-4ea7-8a6a-f4bdd42b1a11.gif)

**Comment by tr7zw** [comment]
Currently "crawling"(technically swimming) is excluded from the animation smoothing. I'll have to test what this might cause.

**Comment by tr7zw** [comment]
Did the test, rotates really fast all over the place, won't fix^^.
