### ISSUE TITLE
Fix player model positioning when sneaking and crawling

### ISSUE THREAD

**Issue by muzikbike** [tr7zw/NotEnoughAnimations#73]
As per #68 this may be out of scope, but it's probably worth bringing this up anyway as the mod does intend to fix many of the problems with player models.

Currently, the player model is positioned incorrectly in certain poses, which is undesirable.

Normal standing: working exactly as expected and included here for comparison's sake
![2022-02-28_16 23 42](https://user-images.githubusercontent.com/52297970/156020561-97607f3c-184a-4426-a87a-3c969c5aebd5.png)

Sneaking: player is slightly offset into the ground (https://bugs.mojang.com/browse/MC-48191)
![2022-02-28_16 23 45](https://user-images.githubusercontent.com/52297970/156020629-e12eab74-0546-471e-86c1-d333da9d6a97.png)

Crawling: player levitates slightly above the ground (https://bugs.mojang.com/browse/MC-202579)
![2022-02-28_16 24 02](https://user-images.githubusercontent.com/52297970/156020700-f59c1468-b329-4d9e-bab6-1486773cb2cd.png)

Fix should be relatively simple: for sneaking, the player model should be moved upwards by a couple of pixels or so such that their feet don't intersect the ground, but are instead flush with it like with standing (this may also fix https://bugs.mojang.com/browse/MC-142684), and for crawling the player model should be moved downwards such that their torso makes direct contact with the block below.

**Comment by tr7zw** [comment]
Thanks for creating all the issues, I'll look more into them the following days, for today I'll be kinda busy with the addon release that I've been waiting for, for over a year https://www.youtube.com/watch?v=Dti_CKADLu4 .

**Comment by tr7zw** [comment]
Hm I guess I can make these two changes an optional thing, cause they will cause issues with for example FirstPerson mod. Will do that after updating all mods to 1.18.2.

**Comment by ohnecksThing** [comment]
The sneaking one is partly intentional, since original sneaking was a little bit higher and it didn't majorly change your hitbox. In 1.14 they made player sneak lower to fit through 1.5 block gap and bent player just a bit more, but not too much because sneaking lower, I guess, might look slightly... painful... but they had to lower player's model sneaking instead so the head would perfectly visually align under a slab. If you'd need to "fix" that, then the best solution might be, I guess, kinda invent a new one(?) Not quite sure about that

**Comment by tr7zw** [comment]
Yea this is a tricky one. Not yet sure if I'll do anything about it, to be honest.

**Comment by muzikbike** [comment]
I'm almost certain that the sneaking bug predates that change.

**Comment by muzikbike** [comment]
...in fact, I can prove that in less than five seconds since the ticket was created in 2014.

**Comment by tr7zw** [comment]
I mean there is no real fixing this one without clipping or floating. Either the face when crawling or feet when sneaking clip the ground, or you have to offset it enough up till the player is floating. 
I think this is a bit out of scope for this mod to look into.
