### ISSUE TITLE
Suggestion: Add an option to hold all items up like the compass/clock

### ISSUE THREAD

**Issue by Hedwig7s** [tr7zw/NotEnoughAnimations#74]
Mainly for First-Person Model
I can't see what I'm holding most of the time
I would also suggest stabilising tool animations so you can see them better while moving and not hold them as high as other items

**Comment by Hedwig7s** [comment]
Also add an option to control how high to hold the item

**Comment by tr7zw** [comment]
Implemented this, the only difference between the config entries and the everything settings is that the arm is allowed to swing. The values in the config like the compass are meant to still be readable while walking, that's why they have all swinging disabled.

**Comment by Hedwig7s** [comment]
> Implemented this, the only difference between the config entries and the everything settings is that the arm is allowed to swing. The values in the config like the compass are meant to still be readable while walking, that's why they have all swinging disabled.

Would recommend allowing the player to disable the swinging and control the holding height per each item or item group (tools, blocks and items). If groups are a bit too much, just allow tools.
The "per each" applies to both suggestions (although I want an option for disabling swinging in general as well)
