### ISSUE TITLE
Suggestion: Make the climbing animation move a bit more

### ISSUE THREAD

**Issue by Hedwig7s** [tr7zw/NotEnoughAnimations#75]
The arms barely move in the current animation
Would be nice to have a longer one with more vertical movement on the arms

**Comment by Hedwig7s** [comment]
It is also bugged to trigger in scaffolding

**Comment by tr7zw** [comment]
Not a bug, intended. Anytime the player climbs the animation players. The bigger question is what would be the correct animation climbing a scaffolding where you just clip through floors^^.

**Comment by tr7zw** [comment]
Made all the parameters configurable, and made them by default a bit more logical for the first person mod + moving a tiny bit more.
