### ISSUE TITLE
( Suggestion ) Ladder sneak pose

### ISSUE THREAD

**Issue by wsesrdtf** [tr7zw/NotEnoughAnimations#78]
![2022-03-20_16 00 45](https://user-images.githubusercontent.com/101512862/159153408-74912183-2e1c-47d7-8465-9ff2b2270eeb.png)
↑ While up & down (first person)

![2022-03-20_16 00 56](https://user-images.githubusercontent.com/101512862/159153411-1bcee6b8-9af1-4a74-9b6c-3456b1f17104.png)
↑ Sneaking (first person)

![2022-03-20_16 17 10](https://user-images.githubusercontent.com/101512862/159153412-daaf7fa3-dbca-4eaa-9c2b-7a81a8895d9c.png)
↑ While up & down (third person)

![2022-03-20_16 17 21](https://user-images.githubusercontent.com/101512862/159153420-0671fafe-e8e6-4b4d-a226-42201d378e36.png)
↑ Sneaking (third person)

If you sneak by pressing the Left Shift button while going up and down the ladder, 
the character's pose changes and stops there. 
The pose at this time looks like Vanilla's sneak pose, 
which is the same as the sneak pose on the ground.

This pose is very awkward because Mojang Minecraft applied the sneak pose from the ground to the ladder. 
So I would like the sneak pose on the ladder to work differently in this mod than on the ground.

The attached image is a better pose that I think is the most natural in Minecraft, 
under the condition that the player model does not change.

![123](https://user-images.githubusercontent.com/101512862/159153581-61e97c71-a7f5-4fee-b297-0a8b1a03ed9c.png)

I'm not a programmer, 
so I don't know if it possible to use the sneak pose differently 
when sneaking on the ground and ladders or vines in Minecraft, 
but if it is possible, 
it would be really nice to see.

**Comment by tr7zw** [comment]
Uhhh this one might be really tricky. Sneaking is kinda deeply coded into the rendering, and expects the head to go down a bit and the back to be at a light angle. But since this is just while on a ladder, this could potentially be doable? Will need some testing.
