### ISSUE TITLE
[Compatibility Suggestion] Add BackSlot

### ISSUE THREAD

**Issue by Akorian** [tr7zw/NotEnoughAnimations#8]
It would be amazing if this mod would get compatibility with the mod BackSlot which adds 2 Slots for tools that can be drawn. It would be amazing to see animations for that.

**Comment by tr7zw** [comment]
Ok reviewing this issue now, I think BackSlot should just add an animation for it. I mean this mod is about fixing vanilla animations, other mods can fix their own animations^^.
