### ISSUE TITLE
( Suggestion ) New rotation locking

### ISSUE THREAD

**Issue by wsesrdtf** [tr7zw/NotEnoughAnimations#80]
It is very surprising that unlike vanilla, 
only the upper body can move independently when rotating the body. 
This creates an environment that is more realistic and immersive in your character.

But it comes with discomfort when holding something in your hand. 
That's especially true when the object is large and covers a larger area of the screen.
For example, when holding a shield and a weapon at the same time.
There is no problem when you stand still and face the front.
But as you move to dodge or attack enemies, 
your shield and sword will often come to the center of the screen and block your view, 
and it becomes causing motion sickness.

You'll have to rotate the screen almost 90 degrees 
to get the shield and sword back into place so they don't block the front. 
Or, you have to walk straight ahead 
without using the left or right buttons at the same time as moving forward. 
This is impossible in the case of complicated moving such as battle.

So this mod has a config option called rotation locking. 
But it just locks the upper body movement like vanilla.

That offsets the benefits of this mod.
So I propose a new rotation locking.
It is to make the locking smooth, 
like the smoothing animation feature.
If you move the camera left or right, 
the upper body follows like a spring.
And it's even better if it comes with a feature that allows you to adjust the strength, 
like a smoothing animation amount feature.

It was inspired by Taekwondo-like moves.
Taekwondo players quickly turn their heads to fix their eyes on the opponent first, 
and then the body rotates along the head to hit the enemy with a kick.

This will definitely reduce 3D motion sickness, 
and at the same time, the independent upper body rotation function, 
which is unique to this mod, can coexist.

**Comment by tr7zw** [comment]
Hm I think I can look into it, just making the body follow the head in a slightly delayed/"springy" fashion shouldn't be that bad to implement.
