### ISSUE TITLE
Additionmto suggestion 74

### ISSUE THREAD

**Issue by Hedwig7s** [tr7zw/NotEnoughAnimations#81]
Just redirecting there
#74

**Comment by tr7zw** [comment]
The holding up feature was just intended to make the compass better usable for first person mod, and to look better with torches. Why suddenly have different holding angles for different types of items? Like what's the usecase?

**Comment by Hedwig7s** [comment]
> The holding up feature was just intended to make the compass better usable for first person mod, and to look better with torches. Why suddenly have different holding angles for different types of items? Like what's the usecase?

Maybe not unique items, but at least tools as they would probably look weird at item height
Also the toggle

**Comment by tr7zw** [comment]
I can't quite follow this. You can either set items to be held up, or set everything to be held up. So what is the exact question/goal^^?

**Comment by Hedwig7s** [comment]
> I can't quite follow this. You can either set items to be held up, or set everything to be held up. So what is the exact question/goal^^?

Ability to disable swinging on tools/all items (button styled off>tools>all like the graphics button)

Control the held height for tools (or don't hold it as high by default (makes pvp easier if the tools are held higher)

Ability to disable holding items up completely

That's it

**Comment by tr7zw** [comment]
> Ability to disable swinging on tools/all items (button styled off>tools>all like the graphics button)

Adding an item to the config disables the swinging.
> Ability to disable holding items up completely

Removing items from the config disables this completely.
I can add a slider for the hold height in general I guess?

**Comment by Hedwig7s** [comment]
> Removing items from the config disables this completely. 
I mean a toggle to enable and disable holding all items higher

**Comment by tr7zw** [comment]
It's in the config screen?

**Comment by Hedwig7s** [comment]
> It's in the config screen?

Ight

**Comment by Hedwig7s** [comment]
Let me know when everything that you wanna add has been added so I know when to build

**Comment by tr7zw** [comment]
?!?
