### ISSUE TITLE
Issue: Fishing Rod string floats a bit off the rod in first person

### ISSUE THREAD

**Issue by Hedwig7s** [tr7zw/NotEnoughAnimations#82]
![2022-03-21_13 38 35](https://user-images.githubusercontent.com/51961150/159262867-a3ebd5e4-304b-4c4b-a549-824806fad4c3.png)

**Comment by tr7zw** [comment]
I think this is a vanilla issue, just more apparent from that perspective. Also not related to NotEnoughAnimations (https://github.com/tr7zw/FirstPersonModel/issues).
