### ISSUE TITLE
Arms Inventory Bug

### ISSUE THREAD

**Issue by Julienraptor01** [tr7zw/NotEnoughAnimations#84]
When you use NEA with Dynamic FPS and Dynamic FPS does his job the arms of the player in the inventory do weird things
[latest.log](https://github.com/tr7zw/NotEnoughAnimations/files/8382206/latest.log)
https://user-images.githubusercontent.com/49841713/160882983-e3be365a-2d29-49a4-9b3f-82fc9d3a3491.mp4

**Comment by tr7zw** [comment]
That's because of how dynamic FPS works. Might be fixed in the next release, or could end up being a won't fix.

**Comment by tr7zw** [comment]
Ok this should really be fixed in the new build.
