### ISSUE TITLE
enableCrawlingAnimation

### ISSUE THREAD

**Issue by wsesrdtf** [tr7zw/NotEnoughAnimations#85]
3dskinlayers-fabric-1.4.2-mc1.18.2.jar
firstperson-fabric-2.1.0-mc1.18-pre1.jar
notenoughanimations-fabric-1.5.0-mc1.18.2.jar

{
  "configVersion": 6,
  "animationSmoothingSpeed": 30.0,
  "holdingItems": [
    "minecraft:clock",
    "minecraft:compass",
    "minecraft:torch",
    "minecraft:lantern",
    "minecraft:soul_torch",
    "minecraft:soul_lantern"
  ],
  "enableAnimationSmoothing": true,
  "enableInWorldMapRendering": true,
  "enableOffhandHiding": true,
  "enableRotationLocking": true,
  "enableLadderAnimation": true,
  "ladderAnimationAmplifier": 0.5,
  "ladderAnimationArmHeight": 1.0,
  "ladderAnimationArmSpeed": 4.0,
  "enableRotateToLadder": false,
  "enableEatDrinkAnimation": true,
  "enableRowBoatAnimation": true,
  "enableHorseAnimation": true,
  "dontHoldItemsInBed": true,
  "freezeArmsInBed": true,
  "keepBodyRotatedWithHead": true,
  "showLastUsedSword": false,
  "sheathSwords": [
    "minecraft:golden_sword",
    "minecraft:iron_sword",
    "minecraft:wooden_sword",
    "minecraft:stone_sword",
    "minecraft:diamond_sword",
    "minecraft:netherite_sword"
  ],
  "enableCrawlingAnimation": true,
  "holdUpAllItems": false,
  "itemSwapAnimation": true
}

![Honeycam 2022-04-01 01-14-50](https://user-images.githubusercontent.com/101512862/161102329-a1ebab72-197d-4446-8847-0e8da506d1ec.gif)

The character just trembles arms and doesn't show normal motion.

**Comment by sparklingfrost** [comment]
same here
[imgur](https://imgur.com/a/hOxYWrZ)
when i move, the animation is stiff, and it spazzes out whether or not im moving.

**Comment by tr7zw** [comment]
Like I said, broken in that version, use the previous release or download the dev build from https://github.com/tr7zw/NotEnoughAnimations/actions/runs/2074231823
