### ISSUE TITLE
Old Running Animation

### ISSUE THREAD

**Issue by KaspianDev** [tr7zw/NotEnoughAnimations#86]
After the update i noticed that leg animation while running is different, I do not like it so I ask for config option to use vanilla one.

**Comment by tr7zw** [comment]
The leg animation is fully vanilla, the only change is that the smoothing is applied to the legs too, so they might not move 100% as high as before(depending on the smoothing setting). I can add a toggle to make the legs teleport again, but it will make other animations look worse(getting in/out of vehicles, using a ladder, sneaking). Temporary you can increase the smoothing speed or disable the smoothing in general.
