### ISSUE TITLE
Problem with body rotation in "Fixed" mode

### ISSUE THREAD

**Issue by x-EEVEELUTIONS-x** [tr7zw/NotEnoughAnimations#87]
When the player model is displayed in the UI, the shadow starts to get buggy (ONLY VISIBLE WITH SHADERS):

![vlcsnap-2022-04-09-21h43m29s555](https://user-images.githubusercontent.com/103344490/162598948-de8a602e-c266-448c-9031-4ebee73a1f17.png)

This happens even with mod UI:

![vlcsnap-2022-04-09-21h43m19s464](https://user-images.githubusercontent.com/103344490/162598971-f7d7e3fc-af8e-470c-8bf4-eda81004aca3.png)

**Comment by Stratdan** [comment]
It's easy to see with first person model mod or with a transparent inventory resource pack
(https://www.curseforge.com/minecraft/mc-mods/first-person-model)
