### ISSUE TITLE
[Suggestion] Elytra flying animation

### ISSUE THREAD

**Issue by RHSD** [tr7zw/NotEnoughAnimations#9]
Vanilla animation swings arms and legs a lot and it looks quite weird in my opinion. It would be really nice if there was a proper gliding animation.

**Comment by tr7zw** [comment]
But there is a proper animation, currently there is just issue https://github.com/tr7zw/FirstPersonModel/issues/96 with the FirstPersonMod that the PaperDoll does move arms/legs when gliding, while in f5 you in fact don't do that.

**Comment by RHSD** [comment]
I am closing this issue until I find what is causing this problem.

**Comment by RHSD** [comment]
It turns out to be an issue if this mod is used with [Abnormals Personality mod ](https://www.curseforge.com/minecraft/mc-mods/personality), which adds few animations too. But I am not sure why it causes a problem with elytra flying as it only adds crawling, sitting and stair climbing animations as far as I know.

**Comment by tr7zw** [comment]
Huh odd. It might get something wrong to place the wrong animations(I also have/had a lot of fun with the elytra animation in the paper doll as you can see with the issue above).

**Comment by RHSD** [comment]
Is this problem manageable on your end (like overriding it, I don't know) or should I open an issue on their github?
