### ISSUE TITLE
[curseforge] allow api usage

### ISSUE THREAD

**Issue by Merith-TK** [tr7zw/NotEnoughAnimations#91]
![image](https://user-images.githubusercontent.com/10422110/170145505-2cab9711-17cc-4f27-893d-5e3d8be36aad.png)

please, this is so that modpack makers that dont use curseforge launcher can still use the api to get the mods downloaded

**Comment by tr7zw** [comment]
See https://github.com/tr7zw/EntityCulling/issues/70#issuecomment-1136968685=

**Comment by tr7zw** [comment]
https://modrinth.com/mod/not-enough-animations As soon as it's approved.
