### ISSUE TITLE
[Suggestion] Animation of the player's head turning.

### ISSUE THREAD

**Issue by 273669975** [tr7zw/NotEnoughAnimations#92]
This is my first time giving advice to a developer, thank you so much, your mods are awesome! I would like to make a suggestion: Is it possible to add the animation of the player's head turning? (I don't know the code, is it possible to implement this?)

**Comment by tr7zw** [comment]
I mean, what kind of animation is missing to the head-turning? Note that the goal of this mod is to feel vanilla, so having a "more animated" movement like the Minecraft trailers would probably not fit in. That would be more something for fresh animations/[trainguys-animation-overhaul](https://github.com/Trainguy9512/trainguys-animation-overhaul)/mo bends.

**Comment by 273669975** [comment]
Thanks for reply，I understand!
