### ISSUE TITLE
Can't Add Items to Config

### ISSUE THREAD

**Issue by Silentfox52** [tr7zw/NotEnoughAnimations#93]
I added a bunch of modded items to the config so that it would be held up like a compass or sheathed but it didn't work. I restarted my game and computer and neither helped so any assistance would be greatly appreciated.

**Comment by tr7zw** [comment]
Uhh I'll have to look into it, worst-case it loads the item list before the mod of the item is loaded.

**Comment by wu4x** [comment]
I'm having a similar issue except I cannot remove items from the config, it forces a specific list of them which you cannot change.

**Comment by tr7zw** [comment]
> I'm having a similar issue except I cannot remove items from the config, it forces a specific list of them which you cannot change.

That sounds even more off? Did you restart your game? Did you change other values? Are you sure the config was valid at the end(if it's invalid, it regenerates)?
