### ISSUE TITLE
Add new animation to shooting bow

### ISSUE THREAD

**Issue by CYYSILVER** [tr7zw/NotEnoughAnimations#96]
currently, shooting bow animation isn't modified? so it look's kind of ridiculous.
if you add animation like this, it would be awesome!
![bow shooting](https://user-images.githubusercontent.com/48582184/173211710-742fcbb2-97e4-44e3-a55c-0f730ccab118.png)
This animation is modded by improved first person which is stop updating in minecraft 1.6
https://www.youtube.com/watch?v=_5Rz0BpEC5Y&t=102s

**Comment by tr7zw** [comment]
This might be a bit out of scope for this mod(more for trainguys animation overhaul mod?). Also, that screenshot is from the normal first-person? I'm currently working on a mod where resource packs can modify first-person animations that way.

**Comment by CYYSILVER** [comment]
> This might be a bit out of scope for this mod(more for trainguys animation overhaul mod?). Also, that screenshot is from the normal first-person? I'm currently working on a mod where resource packs can modify first-person animations that way.

no, it's from a first person mod called "Improved First Person" in 1.6.4 which like "First Person Model" in 1.18.2.

**Comment by tr7zw** [comment]
Yea FirstPerson Mod is by me. The point is that NotEnoughAnimations aims to just fix shortcomings of the 3rd person animations in a vanilla style way. So replacing/modifying animations like running/walking/bow is not really planned.

**Comment by CYYSILVER** [comment]
Oh, okay. Thanks for replying so quickly xD.

**Comment by CYYSILVER** [comment]
> Yea FirstPerson Mod is by me. The point is that NotEnoughAnimations aims to just fix shortcomings of the 3rd person animations in a vanilla style way. So replacing/modifying animations like running/walking/bow is not really planned.

I think it is a vanilla style. because it just changed how to pull the bow (use left hand to hold and right hand to pull) and optimized view in first person just like the Maps in this mod.

Just give some recommendation and thanks again.

**Comment by tr7zw** [comment]
Yea I might add an option to slightly tilt the bow so it doesn't clip with the camera, but probably not much more.

**Comment by tr7zw** [comment]
An alternative bow animation is in the current dev build. Please give it a try and feedback. Other thread to this: https://github.com/tr7zw/FirstPersonModel/issues/56#issuecomment-1412659175

**Comment by tr7zw** [comment]
It's now in all versions.
