### ISSUE TITLE
when i use this in a modpack it doesnt work

### ISSUE THREAD

**Issue by TechOnGFuel** [tr7zw/NotEnoughAnimations#97]
im trying to use NEA in a forge modpack for 1.16.5, but its not working ingame. No other animations are appearing. but, in the mod menu it says its loaded.

**Comment by tr7zw** [comment]
I need more info than that. Also note that 1.16 is not really supported anymore.
Check that you installed TRansliteration Lib, check the settings(if 1.16 had any?), and use a map in 3rd person to check for it working.

**Comment by TechOnGFuel** [comment]
I do have Transliteration LIB, and there are no settings. The map in 3rd person just looks like normal vanilla minecraft.

I don't know if this means anything, but I have a shader pack on and I am using Optifine G7 1.16.5.

**Comment by tr7zw** [comment]
At least from code 1.16 did have a config screen(look in the mod list), https://github.com/tr7zw/NotEnoughAnimations/blob/1.16-legacy/src/main/java/dev/tr7zw/notenoughanimations/config/SharedConfigBuilder.java#L38= but these where all animations that 1.16 had(map holding, holding items up, rotation locking, offhand fixes and buggy animation smoothing). So the 1.16 is not comparable with the current 1.19/18 versions.

**Comment by TechOnGFuel** [comment]
weird. in game its not giving me a config screen. thanks for the help tho :)

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/173243087-a15d2042-5c2c-4f6c-93f1-8d1249c9a1b3.png)
![grafik](https://user-images.githubusercontent.com/5133936/173243121-48d76f1d-5e9d-48ba-a9dc-a218e472a073.png)
Hm the config screen really wasn't implemented, but it certainly works. Do you maybe have some conflicting mod installed like Epic Fight Mod?

**Comment by TechOnGFuel** [comment]
i dont, at least i dont think.
this is my mods list:
Abnormals Delight
AE Additions
AE2 Extras
All The Tweaks
AppleSkin
Applied Energistics 2
Architectury API
ATO - All The Ores
Better Advancements
BetterEnd Reforked
Blood Magic
Blue Skies
Blueprint
Bookshelf
Botany Pots
Botany Pots Tiers
Botany Trees
Bountiful
Caelus API
Catalogue
CaveBiomeAPI
Caves & Cliffs Backport
CC: Tweaked
Chance Cubes
Chargers
Chisel
Chisel & Bits
Clumps
CodeChicken Lib
CoFH Core
Configured
ConnectedTexturesMod
Cooking for Blockheads
Create
Create Confectionery
Croptopia
Cucumber Library
Culinary Construct
Curios API
Curious Elytra
Enchantment Descriptions
Ender Storage
Enderite
EnderTanks
Extreme Reactors
Farmer's Delight
Fast Leaf Decay
First-person Models
Flux Networks
Flywheel
Goblin Traders
GraveStone Mod
Hammer Lib
Hats
Hwyla
iChunUtil
Immersive Cooking
Immersive Engineering
Immersive Petroleum
Immersive Portals
Industrial Foreground
Iron Chests
Iron Furnaces
Iron Jetpacks
JEI Integration
JourneyMap
JEI
JER
Kotlin For Forge
Ma Enchants
Macaw's Bridges
Macaw's Doors
Macaw's Fences and Walls
Macaw's Lights and Lamps
Macaw's Roofs
Macaw's Windows
Mantle
Mekanism
Mekanism Additions
Mekanism Generators
Mekanism Tools
Mod Name Tooltip
Modular Powersuits
Morph
Mouse Tweaks
MrCrayfish's Furniture Mod
Neapolitan
Nether's Delight
Not Enough Animations
Numina
OpenBlocks Elevator
Optifine HD U G7 
Ore Excavation/Veinminer
Pam's HarvestCraft 2 - Crops, Food Core, Food Expansion, and Trees
Patchouli
Pickle Tweaks
Redstone Arsenal
Router Reborn
Scuba Gear
SecretRooms Mod
Selene Lib
ShetiPhianCore
Security Craft
Simple Voice Chat
Skin Layers 3D
Snad
Solar Flux Reborn
Spark
Spartan Shields
Spartan Weaponry
Storage Drawers
Structure Gel API
SuperMartijn642's Core Lib
Supplementaries
The Legend of Herobrine
Thermal Cultivation
Thermal Expansion
Thermal Foundation
Thermal Innovation
Thermal Locomotion
Tinkers Construct
Titanium
TRansliteration LIB
Trash Cans
Tumbleweed
Ultimate Car Mod
Ultimate Plane Mod
Upgraded Core
Upgraded Netherite
Uppers
Wavey Capes
Wawla
Windowlogging
ZeroCore 2

**Comment by TechOnGFuel** [comment]
are any of these mods incompatible?

**Comment by tr7zw** [comment]
I only know parts of them, but anything that replaces the player model usually. But if Skin Layers 3D works, then this mod should work too(at least in newer versions, no clue about 1.16).

**Comment by TechOnGFuel** [comment]
yea, skin layers works.
sux this is happening :/ ty for trying to help tho i appreciate it ✌️
