### ISSUE TITLE
Ladder from other Mod

### ISSUE THREAD

**Issue by ardissaps** [tr7zw/NotEnoughAnimations#99]
Would you like to support ladder from other mods? (like climbable tag or something)

**Comment by tr7zw** [comment]
The issue with the climbable tag is, that it also applies to Scaffolding/Vines etc, where the animation logic won't work/look right. Might be able to get away with a mixed check that it's climbable and is directional like a ladder.

**Comment by tr7zw** [comment]
It's now checking for anything extending LadderBlock or TrapDoorBlock (expandable in the future). This should catch all modded ladders that are implemented based on the vanilla ladder.
